package builderb0y.bigpixel.scripting.types.generators;

import java.io.FileWriter;
import java.io.IOException;

import builderb0y.bigpixel.scripting.types.VectorType;
import builderb0y.bigpixel.scripting.types.VectorType.ComponentType;
import builderb0y.bigpixel.scripting.types.VectorType.GroupShape;

public class RNGGenerator {

	public static String typeName(VectorType type) {
		String name = type.holderClass().getSimpleName();
		if (type.shape == GroupShape.UNIT) return name;
		return "@Vec(" + type.shape.rows + ") " + name;
	}

	public static void main(String[] args) throws IOException {
		StringBuilder file = new StringBuilder(4096);
		file.append(
		//language=java
		"""
		package builderb0y.bigpixel.scripting.types.generated;
		
		import jdk.incubator.vector.*;
		import builderb0y.bigpixel.scripting.types.VectorOperations;
		import builderb0y.bigpixel.scripting.types.VectorType.Vec;
		
		//auto-generated by RNGGenerator.
		@SuppressWarnings({ "unused" })
		public class RngOperations {
		
			public static final long PHI64 = 0x9E3779B97F4A7C15L;
		
			public static long stafford(long z) {
				z = (z ^ (z >>> 30)) * 0xBF58476D1CE4E5B9L;
				z = (z ^ (z >>> 27)) * 0x94D049BB133111EBL;
				return z ^ (z >>> 31);
			}
		
			public static long permute_int(int salt, long seed) {
				return stafford(salt * PHI64 + seed);
			}
		
			public static long permute_long(long salt, long seed) {
				return stafford(salt * PHI64 + seed);
			}
		
			public static long permute_float(float salt, long seed) {
				return stafford(Float.floatToRawIntBits(salt) * PHI64 + seed);
			}
		
			public static long permute_double(double salt, long seed) {
				return stafford(Double.doubleToRawLongBits(salt) * PHI64 + seed);
			}
		
			public static int rng_to_positive_int(long seed) {
				return ((int)(seed)) & 0x7FFF_FFFF;
			}
		
			public static int rng_to_uniform_int(long seed) {
				return (int)(seed);
			}
		
			public static int rng_to_bounded_int(long seed, int max) {
				if (max <= 0) throw new IllegalArgumentException("bound must be positive.");
		
				int mask = max - 1;
				if ((max & mask) == 0) {
					return rng_to_uniform_int(seed) & mask;
				}
				else {
					while (true) {
						int bits = rng_to_positive_int(seed += PHI64);
						int result = bits % max;
						if (bits - result + mask >= 0) return result;
					}
				}
			}
		
			public static int rng_to_ranged_int(long seed, int min, int max) {
				return rng_to_bounded_int(seed, max - min) + min;
			}
		
			public static long rng_to_positive_long(long seed) {
				return seed & 0x7FFF_FFFF_FFFF_FFFFL;
			}
		
			public static long rng_to_uniform_long(long seed) {
				return seed;
			}
		
			public static long rng_to_bounded_long(long seed, long max) {
				if (max <= 0L) throw new IllegalArgumentException("bound must be positive.");
				if (max <= Integer.MAX_VALUE) return (long)(rng_to_bounded_int(seed, (int)(max)));
				long mask = max - 1;
				if ((max & mask) == 0L) {
					return rng_to_uniform_long(seed) & mask;
				}
				else {
					while (true) {
						long bits = rng_to_positive_long(seed += PHI64);
						long result = bits % max;
						if (bits - result + mask >= 0) return result;
					}
				}
			}
		
			public static long rng_to_ranged_long(long seed, long min, long max) {
				return rng_to_bounded_long(seed, max - min) + min;
			}
		
			public static float rng_to_positive_float(long seed) {
				return (seed >>> (64 - 24)) * 0x1.0p-24F;
			}
		
			public static float rng_to_uniform_float(long seed) {
				return (seed >> (64 - 25)) * 0x1.0p-24F;
			}
		
			public static float rng_to_bounded_float(long seed, float max) {
				return rng_to_positive_float(seed) * max;
			}
		
			public static float rng_to_ranged_float(long seed, float min, float max) {
				return rng_to_positive_float(seed) * (max - min) + min;
			}
		
			public static double rng_to_positive_double(long seed) {
				return (seed >>> (64 - 53)) * 0x1.0p-53D;
			}
		
			public static double rng_to_uniform_double(long seed) {
				return (seed >> (64 - 54)) * 0x1.0p-53D;
			}
		
			public static double rng_to_bounded_double(long seed, double max) {
				return rng_to_positive_double(seed) * max;
			}
		
			public static double rng_to_ranged_double(long seed, double min, double max) {
				return rng_to_positive_double(seed) * (max - min) + min;
			}

		""");
		record Sign(String name, String... params) {}
		for (Sign sign : new Sign[] {
			new Sign("positive"),
			new Sign("uniform"),
			new Sign("bounded", "max"),
			new Sign("ranged", "min", "max")
		}) {
			for (VectorType type : VectorType.VALUES) {
				if (type.shape != GroupShape.UNIT && type.componentType != ComponentType.BOOLEAN && type != VectorType.VOID) {
					VectorType unit = VectorType.get(type.componentType, GroupShape.UNIT);
					file
					.append("\tpublic static ")
					.append(typeName(type))
					.append(" rng_to_")
					.append(sign.name)
					.append('_')
					.append(type.name)
					.append("(long seed");
					for (String param : sign.params) {
						file
						.append(", ")
						.append(unit.name)
						.append(' ')
						.append(param);
					}
					file
					.append(") { return VectorOperations.")
					.append(type.name)
					.append("_from");
					for (int i = 0; i < type.shape.rows; i++) {
						file.append('_').append(unit.name);
					}
					file.append('(');
					for (int i = 0; i < type.shape.rows; i++) {
						if (i != 0) file.append(", ");
						file
						.append("rng_to_")
						.append(sign.name)
						.append('_')
						.append(unit.name)
						.append("(permute_int(")
						.append((char)(i + '0'))
						.append(", seed)");
						for (String param : sign.params) {
							file.append(", ").append(param);
						}
						file.append(')');
					}
					file.append("); }\n");
				}
			}
		}
		file.append('}');
		try (FileWriter writer = new FileWriter("src/main/java/builderb0y/bigpixel/scripting/types/generated/RngOperations.java")) {
			writer.write(file.toString());
		}
	}
}