package builderb0y.notgimp.scripting.types.generators;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.function.IntFunction;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

import jdk.incubator.vector.*;

public class MatrixGenerator {

	public static final String PACKAGE = "builderb0y.notgimp.scripting.types.generated";
	public static final File dstPackage = new File("src/main/java/" + PACKAGE.replace('.', '/'));
	public static final int[] dimensionTypes = { 2, 3, 4 };
	public static record Types(Class<?> componentType, Class<?> vectorType, String matrixBaseType) {

		public String matrixType(int dimensions) {
			char digit = (char)(dimensions + '0');
			return this.matrixBaseType + digit + 'x' + digit;
		}
	}
	public static final Types[] componentTypes = {
		new Types(int.class, IntVector.class, "IntMatrix"),
		new Types(long.class, LongVector.class, "LongMatrix"),
		new Types(float.class, FloatVector.class, "FloatMatrix"),
		new Types(double.class, DoubleVector.class, "DoubleMatrix"),
	};

	public final Types types;
	public final String matrixType;
	public final int dimensions;
	public final String species;

	public MatrixGenerator(Types types, int dimensions) {
		this.types = types;
		this.matrixType = types.matrixType(dimensions);
		this.dimensions = dimensions;
		this.species = types.vectorType.getSimpleName() + ".SPECIES_" + (dimensions * (types.componentType == long.class || types.componentType == double.class ? 64 : 32));
	}

	public void run() throws IOException {
		try (FileWriter writer = new FileWriter(new File(dstPackage, this.matrixType + ".java"), StandardCharsets.UTF_8)) {
			writer.write(this.genSource());
		}
	}

	public String loop(IntFunction<String> mapper) {
		return IntStream.range(0, this.dimensions).mapToObj(mapper).collect(Collectors.joining());
	}

	public String loop(IntFunction<String> mapper, String delimitor) {
		return IntStream.range(0, this.dimensions).mapToObj(mapper).collect(Collectors.joining(delimitor));
	}

	public static char letter(int dimension) {
		return (char)(dimension + 'a');
	}

	public static char number(int dimension) {
		return (char)(dimension + '0');
	}

	public String genSource() {
		return STR."""
		package \{PACKAGE};

		import \{this.types.vectorType.getName()};
		import \{VectorOperators.class.getName()};

		//auto-generated by MatrixGenerator. do not touch!
		public record \{this.matrixType}(
		\{this.loop(dimension -> STR."\t\{this.types.vectorType.getSimpleName()} \{letter(dimension)}", ",\n")},
			boolean isTransposed
		) {

			public static \{this.matrixType} columns(
		\{this.loop(dimension -> STR."\t\t\{this.types.vectorType.getSimpleName()} \{letter(dimension)}", ",\n")}
			) {
				return new \{this.matrixType}(\{this.loop(dimension -> String.valueOf(letter(dimension)), ", ")}, false);
			}

			public static \{this.matrixType} rows(
		\{this.loop(dimension -> STR."\t\t\{this.types.vectorType.getSimpleName()} \{letter(dimension)}", ",\n")}
			) {
				return new \{this.matrixType}(\{this.loop(dimension -> String.valueOf(letter(dimension)), ", ")}, true);
			}

			public static \{this.matrixType} diagonal(\{this.types.vectorType.getSimpleName()} diagonal) {
				\{this.types.vectorType.getSimpleName()} zero = \{this.types.vectorType.getSimpleName()}.zero(\{this.species});
				return new \{this.matrixType}(
		\{this.loop(dimension -> STR."\t\t\tzero.withLane(\{number(dimension)}, diagonal.lane(\{number(dimension)}))", ",\n")},
					false
				);
			}

			public static \{this.matrixType} scalar(\{this.types.componentType.getSimpleName()} scalar) {
				\{this.types.vectorType.getSimpleName()} zero = \{this.types.vectorType.getSimpleName()}.zero(\{this.species});
				return new \{this.matrixType}(
		\{this.loop(dimension -> STR."\t\t\tzero.withLane(\{number(dimension)}, scalar)", ",\n")},
					false
				);
			}

			public static \{this.matrixType} fill(\{this.types.componentType.getSimpleName()} value) {
				\{this.types.vectorType.getSimpleName()} filled = \{this.types.vectorType.getSimpleName()}.broadcast(\{this.species}, value);
				return new \{this.matrixType}(\{"filled, ".repeat(this.dimensions)}false);
			}

			public \{this.types.vectorType.getSimpleName()} getComponent(int index) {
				return switch (index) {
		\{this.loop(dimension -> STR."\t\t\tcase \{number(dimension)} -> this.\{letter(dimension)}", ";\n")};
					default -> throw new IndexOutOfBoundsException(index);
				};
			}

			public \{this.matrixType} lanewise(VectorOperators.Unary operator) {
				return new \{this.matrixType}(
		\{this.loop(dimension -> STR."\t\t\tthis.\{letter(dimension)}.lanewise(operator)", ",\n")},
					this.isTransposed
				);
			}

			public \{this.matrixType} lanewise(\{this.types.componentType.getSimpleName()} operand, VectorOperators.Binary operator) {
				return new \{this.matrixType}(
		\{this.loop(dimension -> STR."\t\t\tthis.\{letter(dimension)}.lanewise(operator, operand)", ",\n")},
					this.isTransposed
				);
			}

			public static \{this.matrixType} lanewiseReversed(\{this.types.componentType.getSimpleName()} operand, \{this.matrixType} matrix, VectorOperators.Binary operator) {
				\{this.types.vectorType.getSimpleName()} broadcast = \{this.types.vectorType.getSimpleName()}.broadcast(\{this.species}, operand);
				return new \{this.matrixType}(
		\{this.loop(dimension -> STR."\t\t\tbroadcast.lanewise(operator, matrix.\{letter(dimension)})", ",\n")},
					matrix.isTransposed
				);
			}

			public \{this.matrixType} lanewise(\{this.matrixType} that, VectorOperators.Binary operator) {
				return new \{this.matrixType}(
		\{this.loop(dimension -> STR."\t\t\tthis.\{letter(dimension)}.lanewise(operator, that.\{letter(dimension)})", ",\n")},
					this.isTransposed
				);
			}

		\{
			Arrays.stream(componentTypes).filter((Types types) -> types != this.types).map(type -> STR."""
			\tpublic \{type.matrixBaseType}\{number(this.dimensions)}x\{number(this.dimensions)} \{type.componentType.getSimpleName()}\{number(this.dimensions)}() {
			\t	return new \{type.matrixBaseType}\{number(this.dimensions)}x\{number(this.dimensions)}(
			\{this.loop(dimension -> STR."\t\t\tVectorApi.\{type.componentType.getSimpleName()}\{number(this.dimensions)}(this.\{letter(dimension)})", ",\n")},
			\t		this.isTransposed
			\t	);
			\t}""")
			.collect(Collectors.joining("\n\n"))
		}

			public \{this.matrixType} transpose() {
				return new \{this.matrixType}(
		\{this.loop(dimension -> STR."\t\t\tthis.\{letter(dimension)}", ",\n")},
					!this.isTransposed
				);
			}

			public \{this.types.vectorType.getSimpleName()} transform(\{this.types.vectorType.getSimpleName()} vector) {
				if (this.isTransposed) {
					return VectorApi.\{this.types.componentType.getSimpleName()}\{(char)(this.dimensions + '0')}(
		\{this.loop(dimension -> STR."\t\t\t\tthis.\{letter(dimension)}.mul(vector).reduceLanes(VectorOperators.ADD)", ",\n")}
					);
				}
				else {
					return (
						(\{this.loop(dimension -> STR."this.\{letter(dimension)}.mul(vector.lane(\{number(dimension)}))", ")\n\t\t\t\t.add(")})
					);
				}
			}
		}
		""";
	}

	public static void main(String[] args) throws IOException {
		for (int dimension : dimensionTypes) {
			for (Types types : componentTypes) {
				new MatrixGenerator(types, dimension).run();
			}
		}
	}
}