package builderb0y.notgimp.scripting.types.generators;

import java.io.FileWriter;
import java.io.IOException;
import java.util.Locale;

import jdk.incubator.vector.VectorOperators;

import builderb0y.notgimp.scripting.types.VectorType;
import builderb0y.notgimp.scripting.types.VectorType.ComponentType;
import builderb0y.notgimp.scripting.types.VectorType.GroupShape;

public class OpsGenerator {

	public static final VectorType[] VECTOR_TYPES = {
		VectorType.INT,
		VectorType.INT2,
		VectorType.INT3,
		VectorType.INT4,
		VectorType.LONG,
		VectorType.LONG2,
		VectorType.LONG3,
		VectorType.LONG4,
		VectorType.FLOAT,
		VectorType.FLOAT2,
		VectorType.FLOAT3,
		VectorType.FLOAT4,
		VectorType.DOUBLE,
		VectorType.DOUBLE2,
		VectorType.DOUBLE3,
		VectorType.DOUBLE4,
	};
	public static final ComponentType[] COMPONENT_TYPES = {
		ComponentType.INT,
		ComponentType.LONG,
		ComponentType.FLOAT,
		ComponentType.DOUBLE,
	};
	public static final VectorOperators.Unary[] UNARIES = {
		VectorOperators.NEG,
		VectorOperators.NOT,
		VectorOperators.ABS,
		VectorOperators.SIN,
		VectorOperators.COS,
		VectorOperators.TAN,
		VectorOperators.ASIN,
		VectorOperators.ACOS,
		VectorOperators.ATAN,
		VectorOperators.SINH,
		VectorOperators.COSH,
		VectorOperators.TANH,
		VectorOperators.SQRT,
		VectorOperators.CBRT,
		VectorOperators.EXP,
		VectorOperators.LOG,
	};
	public static final VectorOperators.Binary[] BINARIES = {
		VectorOperators.ADD,
		VectorOperators.SUB,
		VectorOperators.MUL,
		VectorOperators.DIV,
		VectorOperators.POW,
		VectorOperators.AND,
		VectorOperators.OR,
		VectorOperators.XOR,
		VectorOperators.LSHL,
		VectorOperators.LSHR,
		VectorOperators.ASHR,
		VectorOperators.ATAN2,
		VectorOperators.MIN,
		VectorOperators.MAX,
	};

	public static String typeName(VectorType type) {
		String name = type.holderClass().getSimpleName();
		if (type.shape == GroupShape.UNIT) return name;
		return "@Vec(" + type.shape.rows + ") " + name;
	}

	public static int species(VectorType type) {
		int rows = type.shape.rows ;
		if (rows == 3) rows++;
		return Integer.highestOneBit(rows) << (type.componentType.isDoubleWidth ? 6 : 5);
	}

	public static String desc(Class<?> type) {
		return type == long.class ? "L" : type.descriptorString();
	}

	public static char letter(int index) {
		return (char)(index + 'a');
	}

	public static void main(String[] args) throws IOException {
		StringBuilder file = new StringBuilder(8192);
		file.append("""
		package builderb0y.notgimp.scripting.types.generated;
		
		import java.math.*;
		import jdk.incubator.vector.*;
		import builderb0y.notgimp.scripting.types.VectorType.Vec;
		
		//auto-generated by OpsGenerator.
		@SuppressWarnings({
			"unused",
			"StandardVariableNames",
			"ImplicitNumericConversion",
			"NumericCastThatLosesPrecision",
			"MethodParameterNamingConvention",
			"UnpredictableBigDecimalConstructorCall",
		})
		public class VectorOperations {
		
			public static final VectorMask<Integer> INT3_MASK = VectorMask.fromValues(IntVector.SPECIES_128, true, true, true, false);
			public static final VectorMask<Long> LONG3_MASK = VectorMask.fromValues(LongVector.SPECIES_256, true, true, true, false);
			public static final VectorMask<Float> FLOAT3_MASK = VectorMask.fromValues(FloatVector.SPECIES_128, true, true, true, false);
			public static final VectorMask<Double> DOUBLE3_MASK = VectorMask.fromValues(DoubleVector.SPECIES_256, true, true, true, false);
		
		""");
		for (VectorType primary : VECTOR_TYPES) {
			for (ComponentType from : COMPONENT_TYPES) {
				file
				.append("\tpublic static ")
				.append(typeName(primary))
				.append(' ')
				.append(primary.name)
				.append("_from_")
				.append(VectorType.get(from, primary.shape).name)
				.append('(')
				.append(typeName(VectorType.get(from, primary.shape)))
				.append(" a) { return ");

				if (from == primary.componentType) {
					file.append("a; }\n");
				}
				else if (primary.shape == GroupShape.UNIT) {
					file
					.append('(')
					.append(primary.holderClass().getSimpleName())
					.append(')')
					.append("a; }\n");
				}
				else if (primary.componentType.isDoubleWidth == from.isDoubleWidth) {
					file
					.append('(')
					.append(primary.holderClass().getSimpleName())
					.append(')')
					.append("a.convert(VectorOperators.")
					.append(desc(from.holderClass(GroupShape.UNIT)))
					.append('2')
					.append(desc(primary.componentType.holderClass(GroupShape.UNIT)))
					.append(", 0); }\n");
				}
				else {
					file
					.append('(')
					.append(primary.holderClass().getSimpleName())
					.append(')')
					.append("a.convertShape(VectorOperators.")
					.append(desc(from.holderClass(GroupShape.UNIT)))
					.append('2')
					.append(desc(primary.componentType.holderClass(GroupShape.UNIT)))
					.append(", ")
					.append(primary.holderClass().getSimpleName())
					.append(".SPECIES_")
					.append(species(primary))
					.append(", 0); }\n");
				}
			}
			if (primary.shape != GroupShape.UNIT) {
				VectorType component = VectorType.get(primary.componentType, GroupShape.UNIT);
				file
				.append("\tpublic static ")
				.append(typeName(primary))
				.append(' ')
				.append(primary.name)
				.append("_from_")
				.append(component.name)
				.append('(')
				.append(component.holderClass().getSimpleName())
				.append(" a) { return ")
				.append(primary.holderClass().getSimpleName())
				.append(".broadcast(")
				.append(primary.holderClass().getSimpleName())
				.append(".SPECIES_")
				.append(species(primary))
				.append(", a); } \n");

				file
				.append("\tpublic static ")
				.append(typeName(primary))
				.append(' ')
				.append(primary.name)
				.append("_from");
				for (int row = 0; row < primary.shape.rows; row++) {
					file.append('_').append(component.name);
				}
				file.append('(');
				for (int row = 0; row < primary.shape.rows; row++) {
					if (row != 0) file.append(", ");
					file
					.append(component.holderClass().getSimpleName())
					.append(' ')
					.append(letter(row));
				}
				file
				.append(") { return ")
				.append(primary.holderClass().getSimpleName())
				.append(".fromArray(")
				.append(primary.holderClass().getSimpleName())
				.append(".SPECIES_")
				.append(species(primary))
				.append(", new ")
				.append(component.holderClass().getSimpleName())
				.append("[] { ");
				for (int row = 0; row < primary.shape.rows; row++) {
					if (row != 0) file.append(", ");
					file.append(letter(row));
				}
				if (primary.shape.rows == 3) {
					file.append(", 0");
				}
				file.append(" }, 0); }\n");
			}
			file.append('\n');
			for (VectorOperators.Unary operator : UNARIES) {
				if (operator.compatibleWith(primary.componentType.holderClass(GroupShape.UNIT))) {
					file
					.append("\tpublic static ")
					.append(typeName(primary))
					.append(' ')
					.append(operator.name().toLowerCase(Locale.ROOT))
					.append('_')
					.append(primary.name)
					.append('(')
					.append(typeName(primary))
					.append(" a) { return ");
					switch (primary.shape) {
						case UNIT -> {
							if (operator == VectorOperators.NEG) file.append("-a; }\n");
							else if (operator == VectorOperators.NOT) file.append("~a; }\n");
							else if (operator == VectorOperators.ABS) file.append("Math.abs(a); }\n");
							else {
								if (!primary.componentType.isDoubleWidth) {
									file.append('(').append(primary.holderClass().getSimpleName()).append(')');
								}
								file.append("Math.").append(operator.operatorName()).append("(a); }\n");
							}
						}
						case VEC2, VEC3, VEC4 -> {
							file.append("a.lanewise(VectorOperators.").append(operator.name()).append("); }\n");
						}
					}
				}
			}
			file.append('\n');
			for (VectorType secondary : VECTOR_TYPES) {
				if (primary.componentType == secondary.componentType && (primary.shape == GroupShape.UNIT || secondary.shape == GroupShape.UNIT || primary.shape == secondary.shape)) {
					for (VectorOperators.Binary operator : BINARIES) {
						if (operator.compatibleWith(primary.componentType.holderClass(GroupShape.UNIT))) {
							if (
								(operator == VectorOperators.LSHL || operator == VectorOperators.LSHR || operator == VectorOperators.ASHR) &&
								(primary.componentType == ComponentType.FLOAT || primary.componentType == ComponentType.DOUBLE)
							) {
								continue; //workaround a bug in vector API.
							}
							file
							.append("\tpublic static ")
							.append(typeName(primary.shape == GroupShape.UNIT ? secondary : primary))
							.append(' ')
							.append(operator.name().toLowerCase(Locale.ROOT))
							.append('_')
							.append(primary.name)
							.append('_')
							.append(secondary.name)
							.append('(')
							.append(typeName(primary))
							.append(" a, ")
							.append(typeName(secondary))
							.append(" b) { return ");
							if (primary.shape == GroupShape.UNIT) {
								if (secondary.shape == GroupShape.UNIT) {
									if (operator == VectorOperators.POW) {
										if (primary.componentType == ComponentType.FLOAT) {
											file.append("(float)");
										}
										file.append("Math.").append(operator.operatorName()).append("(a, b); }\n");
									}
									else if (operator == VectorOperators.ATAN2) {
										if (primary.componentType == ComponentType.FLOAT) {
											file.append("(float)");
										}
										file.append("Math.").append(operator.operatorName()).append("(b, a); }\n");
									}
									else if (operator == VectorOperators.MIN || operator == VectorOperators.MAX) {
										file.append("Math.").append(operator.operatorName()).append("(a, b); }\n");
									}
									else {
										file.append("a ").append(operator.operatorName()).append(" b; }\n");
									}
								}
								else {
									file
									.append(secondary.holderClass().getSimpleName())
									.append(".broadcast(")
									.append(secondary.holderClass().getSimpleName())
									.append(".SPECIES_")
									.append(species(secondary))
									.append(", a).lanewise(VectorOperators.")
									.append(operator.name())
									.append(", b");
									if (operator == VectorOperators.DIV && (primary.componentType == ComponentType.INT || primary.componentType == ComponentType.LONG)) {
										file.append(", ").append(primary.componentType.name()).append("3_MASK");
									}
									file.append("); }\n");
								}
							}
							else {
								file
								.append("a.lanewise(VectorOperators.")
								.append(operator.name())
								.append(", b");
								if (operator == VectorOperators.DIV && (primary.componentType == ComponentType.INT || primary.componentType == ComponentType.LONG)) {
									file.append(", ").append(primary.componentType.name()).append("3_MASK");
								}
								file.append("); }\n");
							}
						}
					}
				}
			}
			file.append('\n');
			boolean newline = false;
			if (primary.shape != GroupShape.UNIT) {
				newline = true;

				file
				.append("\tpublic static ")
				.append(primary.componentType.holderClass(GroupShape.UNIT).getSimpleName())
				.append(" dot_")
				.append(primary.name)
				.append('_')
				.append(primary.name)
				.append('(')
				.append(typeName(primary))
				.append(" a, ")
				.append(typeName(primary))
				.append(" b) { return a.mul(b).reduceLanes(VectorOperators.ADD); }\n");

				file
				.append("\tpublic static ")
				.append(primary.componentType.holderClass(GroupShape.UNIT).getSimpleName())
				.append(" lengthSquared_")
				.append(primary.name)
				.append('(')
				.append(typeName(primary))
				.append(" a) { return dot_")
				.append(primary.name)
				.append('_')
				.append(primary.name)
				.append("(a, a); }\n");

				if (primary.componentType.isFloatingPoint) {
					file
					.append("\tpublic static ")
					.append(primary.componentType.holderClass(GroupShape.UNIT).getSimpleName())
					.append(" length_")
					.append(primary.name)
					.append('(')
					.append(typeName(primary))
					.append(" a) { return ");
					if (primary.componentType.isSingleWidth()) {
						file.append("(float)");
					}
					file
					.append("Math.sqrt(dot_")
					.append(primary.name)
					.append('_')
					.append(primary.name)
					.append("(a, a)); }\n");

					file
					.append("\tpublic static ")
					.append(typeName(primary))
					.append(" normalize_")
					.append(primary.name)
					.append('(')
					.append(typeName(primary))
					.append(" a) { return a.div(length_")
					.append(primary.name)
					.append("(a)); }\n");
				}
			}
			if (primary.componentType.isFloatingPoint) {
				newline = true;

				file
				.append("\tpublic static ")
				.append(typeName(primary))
				.append(" mix_")
				.append(primary.name)
				.append('_')
				.append(primary.name)
				.append('_')
				.append(primary.name)
				.append('(')
				.append(typeName(primary))
				.append(" a, ")
				.append(typeName(primary))
				.append(" b, ")
				.append(typeName(primary))
				.append(" f) { return ");

				if (primary.shape != GroupShape.UNIT) {
					file.append("b.sub(a).mul(f).add(a); }\n");

					file
					.append("\tpublic static ")
					.append(typeName(primary))
					.append(" mix_")
					.append(primary.name)
					.append('_')
					.append(primary.name)
					.append('_')
					.append(VectorType.get(primary.componentType, GroupShape.UNIT).name)
					.append('(')
					.append(typeName(primary))
					.append(" a, ")
					.append(typeName(primary))
					.append(" b, ")
					.append(primary.componentType.holderClass(GroupShape.UNIT).getSimpleName())
					.append(" f) { return b.sub(a).mul(f).add(a); }\n");
				}
				else {
					file.append("(b - a) * f + a; }\n");
				}
			}
			if (newline) file.append('\n');
		}
		file.append("""
			public static BigInteger neg_bigint(BigInteger a) { return a.negate(); }
			public static BigInteger not_bigint(BigInteger a) { return a.not(); }
			public static BigInteger abs_bigint(BigInteger a) { return a.abs(); }
		
			public static BigInteger add_bigint_bigint(BigInteger a, BigInteger b) { return a.add(b); }
			public static BigInteger sub_bigint_bigint(BigInteger a, BigInteger b) { return a.subtract(b); }
			public static BigInteger mul_bigint_bigint(BigInteger a, BigInteger b) { return a.multiply(b); }
			public static BigInteger div_bigint_bigint(BigInteger a, BigInteger b) { return a.divide(b); }
			public static BigInteger pow_bigint_bigint(BigInteger a, BigInteger b) { return a.pow(b.intValueExact()); }
			public static BigInteger and_bigint_bigint(BigInteger a, BigInteger b) { return a.and(b); }
			public static BigInteger or_bigint_bigint(BigInteger a, BigInteger b) { return a.or(b); }
			public static BigInteger xor_bigint_bigint(BigInteger a, BigInteger b) { return a.xor(b); }
			public static BigInteger lshl_bigint_bigint(BigInteger a, BigInteger b) { return a.shiftLeft(b.intValueExact()); }
			public static BigInteger ashr_bigint_bigint(BigInteger a, BigInteger b) { return a.shiftRight(b.intValueExact()); }
			public static BigInteger min_bigint_bigint(BigInteger a, BigInteger b) { return a.min(b); }
			public static BigInteger max_bigint_bigint(BigInteger a, BigInteger b) { return a.max(b); }

			public static BigDecimal neg_bigdec(BigDecimal a) { return a.negate(); }
			public static BigDecimal abs_bigdec(BigDecimal a) { return a.abs(); }
			public static BigDecimal sin_bigdec(BigDecimal a) { return new BigDecimal(Math.sin(a.doubleValue())); }
			public static BigDecimal cos_bigdec(BigDecimal a) { return new BigDecimal(Math.cos(a.doubleValue())); }
			public static BigDecimal tan_bigdec(BigDecimal a) { return new BigDecimal(Math.tan(a.doubleValue())); }
			public static BigDecimal asin_bigdec(BigDecimal a) { return new BigDecimal(Math.asin(a.doubleValue())); }
			public static BigDecimal acos_bigdec(BigDecimal a) { return new BigDecimal(Math.acos(a.doubleValue())); }
			public static BigDecimal atan_bigdec(BigDecimal a) { return new BigDecimal(Math.atan(a.doubleValue())); }
			public static BigDecimal sinh_bigdec(BigDecimal a) { return new BigDecimal(Math.sinh(a.doubleValue())); }
			public static BigDecimal cosh_bigdec(BigDecimal a) { return new BigDecimal(Math.cosh(a.doubleValue())); }
			public static BigDecimal tanh_bigdec(BigDecimal a) { return new BigDecimal(Math.tanh(a.doubleValue())); }
			public static BigDecimal sqrt_bigdec(BigDecimal a) { return a.sqrt(MathContext.DECIMAL128); }
			public static BigDecimal cbrt_bigdec(BigDecimal a) { return new BigDecimal(Math.cbrt(a.doubleValue())); }
			public static BigDecimal exp_bigdec(BigDecimal a) { return new BigDecimal(Math.exp(a.doubleValue())); }
			public static BigDecimal log_bigdec(BigDecimal a) { return new BigDecimal(Math.log(a.doubleValue())); }
		
			public static BigDecimal add_bigdec_bigdec(BigDecimal a, BigDecimal b) { return a.add(b); }
			public static BigDecimal sub_bigdec_bigdec(BigDecimal a, BigDecimal b) { return a.subtract(b); }
			public static BigDecimal mul_bigdec_bigdec(BigDecimal a, BigDecimal b) { return a.multiply(b, MathContext.DECIMAL128); }
			public static BigDecimal div_bigdec_bigdec(BigDecimal a, BigDecimal b) { return a.divide(b, MathContext.DECIMAL128); }
			public static BigDecimal pow_bigdec_bigdec(BigDecimal a, BigDecimal b) { return new BigDecimal(Math.pow(a.doubleValue(), b.doubleValue())); }
			public static BigDecimal atan2_bigdec_bigdec(BigDecimal a, BigDecimal b) { return new BigDecimal(Math.atan2(a.doubleValue(), b.doubleValue())); }
			public static BigDecimal min_bigdec_bigdec(BigDecimal a, BigDecimal b) { return a.min(b); }
			public static BigDecimal max_bigdec_bigdec(BigDecimal a, BigDecimal b) { return a.max(b); }
		
			public static BigDecimal mix_bigdec_bigdec_bigdec(BigDecimal a, BigDecimal b, BigDecimal f) { return b.subtract(a).multiply(f, MathContext.DECIMAL128).add(a); }
		}""");
		try (FileWriter writer = new FileWriter("src/main/java/builderb0y/notgimp/scripting/types/generated/VectorOperations.java")) {
			writer.write(file.toString());
		}
	}
}