package builderb0y.notgimp.scripting.types.generators;

import java.io.FileWriter;
import java.io.IOException;
import java.util.Locale;

import jdk.incubator.vector.VectorOperators;

import builderb0y.notgimp.scripting.types.VectorType;
import builderb0y.notgimp.scripting.types.VectorType.ComponentType;
import builderb0y.notgimp.scripting.types.VectorType.GroupShape;

public class OpsGenerator {

	public static final VectorType[] VECTOR_TYPES = {
		VectorType.INT,
		VectorType.INT2,
		VectorType.INT3,
		VectorType.INT4,
		VectorType.LONG,
		VectorType.LONG2,
		VectorType.LONG3,
		VectorType.LONG4,
		VectorType.FLOAT,
		VectorType.FLOAT2,
		VectorType.FLOAT3,
		VectorType.FLOAT4,
		VectorType.DOUBLE,
		VectorType.DOUBLE2,
		VectorType.DOUBLE3,
		VectorType.DOUBLE4,
	};
	public static final ComponentType[] COMPONENT_TYPES = {
		ComponentType.INT,
		ComponentType.LONG,
		ComponentType.FLOAT,
		ComponentType.DOUBLE,
	};
	public static final VectorOperators.Unary[] UNARIES = {
		VectorOperators.NEG,
		VectorOperators.NOT,
		VectorOperators.ABS,
		VectorOperators.SIN,
		VectorOperators.COS,
		VectorOperators.TAN,
		VectorOperators.ASIN,
		VectorOperators.ACOS,
		VectorOperators.ATAN,
		VectorOperators.SINH,
		VectorOperators.COSH,
		VectorOperators.TANH,
		VectorOperators.SQRT,
		VectorOperators.CBRT,
		VectorOperators.EXP,
		VectorOperators.LOG,
	};
	public static final VectorOperators.Binary[] BINARIES = {
		VectorOperators.ADD,
		VectorOperators.SUB,
		VectorOperators.MUL,
		VectorOperators.POW,
		VectorOperators.AND,
		VectorOperators.OR,
		VectorOperators.XOR,
		VectorOperators.LSHL,
		VectorOperators.LSHR,
		VectorOperators.ASHR,
		VectorOperators.ATAN2,
		VectorOperators.MIN,
		VectorOperators.MAX,
	};
	public static final ExtraOperator[] EXTRA_UNARIES = {
		new ExtraOperator(
			"floor",
			null,
			null,
			"return (float)Math.floor(a);",
			"return Math.floor(a);"
		),
		new ExtraOperator(
			"ceil",
			null,
			null,
			"return (float)Math.ceil(a);",
			"return Math.ceil(a);"
		),
		new ExtraOperator(
			"fract",
			null,
			null,
			"return a - (float)Math.floor(a);",
			"return a - Math.floor(a);"
		),
	};
	public static final ExtraOperator[] EXTRA_BINARIES = {
		new ExtraOperator(
			"div",
			"return Math.floorDiv(a, b);",
			"return Math.floorDiv(a, b);",
			"return a / b;",
			"return a / b;"
		),
		new ExtraOperator(
			"mod",
			"return Math.floorMod(a, b);",
			"return Math.floorMod(a, b);",
			//floorMod() not available for floats and doubles,
			//and % doesn't do the same thing.
			"float r = a % b; return (Float.floatToRawIntBits(a) ^ Float.floatToRawIntBits(b)) < 0 && r != 0 ? r + b : r;",
			"double r = a % b; return (Double.doubleToRawLongBits(a) ^ Double.doubleToRawLongBits(b)) < 0L && r != 0 ? r + b : r;"
		)
	};

	public static record ExtraOperator(
		String name,
		String intImplementation,
		String longImplementation,
		String floatImplementation,
		String doubleImplementation
	) {}

	public static String typeName(VectorType type) {
		String name = type.holderClass().getSimpleName();
		if (type.shape == GroupShape.UNIT) return name;
		return "@Vec(" + type.shape.rows + ") " + name;
	}

	public static int species(VectorType type) {
		int rows = type.shape.rows ;
		if (rows == 3) rows++;
		return Integer.highestOneBit(rows) << (type.componentType.isDoubleWidth ? 6 : 5);
	}

	public static String desc(Class<?> type) {
		return type == long.class ? "L" : type.descriptorString();
	}

	public static char letter(int index) {
		return (char)(index + 'a');
	}

	public static void main(String[] args) throws IOException {
		StringBuilder file = new StringBuilder(8192);
		file.append("""
		package builderb0y.notgimp.scripting.types.generated;
		
		import jdk.incubator.vector.*;
		import builderb0y.notgimp.scripting.types.VectorType.Vec;
		
		//auto-generated by OpsGenerator.
		@SuppressWarnings({
			"unused",
			"StandardVariableNames",
			"ImplicitNumericConversion",
			"NumericCastThatLosesPrecision",
			"MethodParameterNamingConvention",
		})
		public class VectorOperations {
		
			public static final VectorMask<Integer> INT3_MASK = VectorMask.fromValues(IntVector.SPECIES_128, true, true, true, false);
			public static final VectorMask<Long> LONG3_MASK = VectorMask.fromValues(LongVector.SPECIES_256, true, true, true, false);
			public static final VectorMask<Float> FLOAT3_MASK = VectorMask.fromValues(FloatVector.SPECIES_128, true, true, true, false);
			public static final VectorMask<Double> DOUBLE3_MASK = VectorMask.fromValues(DoubleVector.SPECIES_256, true, true, true, false);
		
		""");
		for (VectorType primary : VECTOR_TYPES) {
			VectorType primaryUnit = VectorType.get(primary.componentType, GroupShape.UNIT);
			for (ComponentType from : COMPONENT_TYPES) {
				file
				.append("\tpublic static ")
				.append(typeName(primary))
				.append(' ')
				.append(primary.name)
				.append("_from_")
				.append(VectorType.get(from, primary.shape).name)
				.append('(')
				.append(typeName(VectorType.get(from, primary.shape)))
				.append(" a) { return ");

				if (from == primary.componentType) {
					file.append("a; }\n");
				}
				else if (primary.shape == GroupShape.UNIT) {
					file
					.append('(')
					.append(primary.holderClass().getSimpleName())
					.append(')')
					.append("a; }\n");
				}
				else if (primary.componentType.isDoubleWidth == from.isDoubleWidth) {
					file
					.append('(')
					.append(primary.holderClass().getSimpleName())
					.append(')')
					.append("a.convert(VectorOperators.")
					.append(desc(from.holderClass(GroupShape.UNIT)))
					.append('2')
					.append(desc(primary.componentType.holderClass(GroupShape.UNIT)))
					.append(", 0); }\n");
				}
				else {
					file
					.append('(')
					.append(primary.holderClass().getSimpleName())
					.append(')')
					.append("a.convertShape(VectorOperators.")
					.append(desc(from.holderClass(GroupShape.UNIT)))
					.append('2')
					.append(desc(primary.componentType.holderClass(GroupShape.UNIT)))
					.append(", ")
					.append(primary.holderClass().getSimpleName())
					.append(".SPECIES_")
					.append(species(primary))
					.append(", 0); }\n");
				}
			}
			if (primary.shape != GroupShape.UNIT) {
				file
				.append("\tpublic static ")
				.append(typeName(primary))
				.append(' ')
				.append(primary.name)
				.append("_from_")
				.append(primaryUnit.name)
				.append('(')
				.append(primaryUnit.holderClass().getSimpleName())
				.append(" a) { return ")
				.append(primary.holderClass().getSimpleName())
				.append(".broadcast(")
				.append(primary.holderClass().getSimpleName())
				.append(".SPECIES_")
				.append(species(primary))
				.append(", a); }\n");

				file
				.append("\tpublic static ")
				.append(typeName(primary))
				.append(' ')
				.append(primary.name)
				.append("_from");
				for (int row = 0; row < primary.shape.rows; row++) {
					file.append('_').append(primaryUnit.name);
				}
				file.append('(');
				for (int row = 0; row < primary.shape.rows; row++) {
					if (row != 0) file.append(", ");
					file
					.append(primaryUnit.holderClass().getSimpleName())
					.append(' ')
					.append(letter(row));
				}
				file
				.append(") { return ")
				.append(primary.holderClass().getSimpleName())
				.append(".fromArray(")
				.append(primary.holderClass().getSimpleName())
				.append(".SPECIES_")
				.append(species(primary))
				.append(", new ")
				.append(primaryUnit.holderClass().getSimpleName())
				.append("[] { ");
				for (int row = 0; row < primary.shape.rows; row++) {
					if (row != 0) file.append(", ");
					file.append(letter(row));
				}
				if (primary.shape.rows == 3) {
					file.append(", 0");
				}
				file.append(" }, 0); }\n");
			}
			file.append('\n');
			for (VectorOperators.Unary operator : UNARIES) {
				if (operator.compatibleWith(primary.componentType.holderClass(GroupShape.UNIT))) {
					file
					.append("\tpublic static ")
					.append(typeName(primary))
					.append(' ')
					.append(operator.name().toLowerCase(Locale.ROOT))
					.append('_')
					.append(primary.name)
					.append('(')
					.append(typeName(primary))
					.append(" a) { return ");
					if (primary.shape == GroupShape.UNIT) {
						if (operator == VectorOperators.NEG) file.append("-a; }\n");
						else if (operator == VectorOperators.NOT) file.append("~a; }\n");
						else if (operator == VectorOperators.ABS) file.append("Math.abs(a); }\n");
						else {
							if (!primary.componentType.isDoubleWidth) {
								file.append('(').append(primary.holderClass().getSimpleName()).append(')');
							}
							file.append("Math.").append(operator.operatorName()).append("(a); }\n");
						}
					}
					else {
						file.append("a.lanewise(VectorOperators.").append(operator.name()).append("); }\n");
					}
				}
			}
			for (ExtraOperator operator : EXTRA_UNARIES) {
				String implementation = switch (primary.componentType) {
					case INT -> operator.intImplementation;
					case LONG -> operator.longImplementation;
					case FLOAT -> operator.floatImplementation;
					case DOUBLE -> operator.doubleImplementation;
					case BOOLEAN -> null;
					case VOID -> null;
				};
				if (implementation != null) {
					file
					.append("\tpublic static ")
					.append(typeName(primary))
					.append(' ')
					.append(operator.name)
					.append('_')
					.append(primary.name)
					.append('(')
					.append(typeName(primary))
					.append(" a) { ");
					if (primary.shape == GroupShape.UNIT) {
						file.append(implementation).append(" }\n");
					}
					else {
						file.append("return ").append(primary.name).append("_from");
						for (int lane = 0; lane < primary.shape.rows; lane++) {
							file.append('_').append(primaryUnit.name);
						}
						file.append('(');
						for (int lane = 0; lane < primary.shape.rows; lane++) {
							if (lane != 0) file.append(", ");
							file
							.append(operator.name)
							.append('_')
							.append(primaryUnit.name)
							.append("(a.lane(")
							.append((char)(lane + '0'))
							.append("))");
						}
						file.append("); }\n");
					}
				}
			}
			file.append('\n');
			for (VectorType secondary : VECTOR_TYPES) {
				if (primary.componentType == secondary.componentType && (primary.shape == GroupShape.UNIT || secondary.shape == GroupShape.UNIT || primary.shape == secondary.shape)) {
					VectorType secondaryUnit = VectorType.get(secondary.componentType, GroupShape.UNIT);
					for (VectorOperators.Binary operator : BINARIES) {
						if (operator.compatibleWith(primary.componentType.holderClass(GroupShape.UNIT))) {
							if (
								(operator == VectorOperators.LSHL || operator == VectorOperators.LSHR || operator == VectorOperators.ASHR) &&
								(primary.componentType == ComponentType.FLOAT || primary.componentType == ComponentType.DOUBLE)
							) {
								continue; //workaround a bug in vector API.
							}
							file
							.append("\tpublic static ")
							.append(typeName(primary.shape == GroupShape.UNIT ? secondary : primary))
							.append(' ')
							.append(operator.name().toLowerCase(Locale.ROOT))
							.append('_')
							.append(primary.name)
							.append('_')
							.append(secondary.name)
							.append('(')
							.append(typeName(primary))
							.append(" a, ")
							.append(typeName(secondary))
							.append(" b) { return ");
							if (primary.shape == GroupShape.UNIT) {
								if (secondary.shape == GroupShape.UNIT) {
									if (operator == VectorOperators.POW) {
										if (primary.componentType == ComponentType.FLOAT) {
											file.append("(float)");
										}
										file.append("Math.").append(operator.operatorName()).append("(a, b); }\n");
									}
									else if (operator == VectorOperators.ATAN2) {
										if (primary.componentType == ComponentType.FLOAT) {
											file.append("(float)");
										}
										file.append("Math.").append(operator.operatorName()).append("(b, a); }\n");
									}
									else if (operator == VectorOperators.MIN || operator == VectorOperators.MAX) {
										file.append("Math.").append(operator.operatorName()).append("(a, b); }\n");
									}
									else {
										file.append("a ").append(operator.operatorName()).append(" b; }\n");
									}
								}
								else {
									file
									.append(secondary.holderClass().getSimpleName())
									.append(".broadcast(")
									.append(secondary.holderClass().getSimpleName())
									.append(".SPECIES_")
									.append(species(secondary))
									.append(", a).lanewise(VectorOperators.")
									.append(operator.name())
									.append(", b");
									if (operator == VectorOperators.DIV && (primary.componentType == ComponentType.INT || primary.componentType == ComponentType.LONG)) {
										file.append(", ").append(primary.componentType.name()).append("3_MASK");
									}
									file.append("); }\n");
								}
							}
							else {
								file
								.append("a.lanewise(VectorOperators.")
								.append(operator.name())
								.append(", b");
								if (operator == VectorOperators.DIV && (primary.componentType == ComponentType.INT || primary.componentType == ComponentType.LONG)) {
									file.append(", ").append(primary.componentType.name()).append("3_MASK");
								}
								file.append("); }\n");
							}
						}
					}
					for (ExtraOperator operator : EXTRA_BINARIES) {
						String implementation = switch (primary.componentType) {
							case INT -> operator.intImplementation;
							case LONG -> operator.longImplementation;
							case FLOAT -> operator.floatImplementation;
							case DOUBLE -> operator.doubleImplementation;
							case BOOLEAN -> null;
							case VOID -> null;
						};
						if (implementation != null) {
							VectorType longer = primary.shape == GroupShape.UNIT ? secondary : primary;
							file
								.append("\tpublic static ")
								.append(typeName(longer))
								.append(' ')
								.append(operator.name)
								.append('_')
								.append(primary.name)
								.append('_')
								.append(secondary.name)
								.append('(')
								.append(typeName(primary))
								.append(" a, ")
								.append(typeName(secondary))
								.append(" b) { ");
							if (primary.shape == GroupShape.UNIT && secondary.shape == GroupShape.UNIT) {
								file.append(implementation).append(" }\n");
							}
							else {
								file.append("return ").append(longer.name).append("_from");
								for (int lane = 0; lane < longer.shape.rows; lane++) {
									file
									.append('_')
									.append(primaryUnit.name);
								}
								file.append('(');
								for (int lane = 0; lane < longer.shape.rows; lane++) {
									if (lane != 0) file.append(", ");
									file
									.append(operator.name)
									.append('_')
									.append(primaryUnit.name)
									.append('_')
									.append(primaryUnit.name)
									.append("(a");
									if (primary.shape != GroupShape.UNIT) {
										file
										.append(".lane(")
										.append((char)(lane + '0'))
										.append(')');
									}
									file.append(", b");
									if (secondary.shape != GroupShape.UNIT) {
										file
										.append(".lane(")
										.append((char)(lane + '0'))
										.append(')');
									}
									file.append(')');
								}
								file.append("); }\n");
							}
						}
					}
				}
			}
			file.append('\n');
			boolean newline = false;
			if (primary.shape != GroupShape.UNIT) {
				newline = true;

				file
				.append("\tpublic static ")
				.append(primary.componentType.holderClass(GroupShape.UNIT).getSimpleName())
				.append(" dot_")
				.append(primary.name)
				.append('_')
				.append(primary.name)
				.append('(')
				.append(typeName(primary))
				.append(" a, ")
				.append(typeName(primary))
				.append(" b) { return a.mul(b).reduceLanes(VectorOperators.ADD");
				if (primary.shape.rows == 3) {
					file.append(", ").append(primary.name.toUpperCase(Locale.ROOT)).append("_MASK");
				}
				file.append("); }\n");

				file
				.append("\tpublic static ")
				.append(primary.componentType.holderClass(GroupShape.UNIT).getSimpleName())
				.append(" lengthSquared_")
				.append(primary.name)
				.append('(')
				.append(typeName(primary))
				.append(" a) { return dot_")
				.append(primary.name)
				.append('_')
				.append(primary.name)
				.append("(a, a); }\n");

				if (primary.componentType.isFloatingPoint) {
					file
					.append("\tpublic static ")
					.append(primary.componentType.holderClass(GroupShape.UNIT).getSimpleName())
					.append(" length_")
					.append(primary.name)
					.append('(')
					.append(typeName(primary))
					.append(" a) { return ");
					if (primary.componentType.isSingleWidth()) {
						file.append("(float)");
					}
					file
					.append("Math.sqrt(dot_")
					.append(primary.name)
					.append('_')
					.append(primary.name)
					.append("(a, a)); }\n");

					file
					.append("\tpublic static ")
					.append(typeName(primary))
					.append(" normalize_")
					.append(primary.name)
					.append('(')
					.append(typeName(primary))
					.append(" a) { return a.div(length_")
					.append(primary.name)
					.append("(a)); }\n");
				}
			}
			if (primary.componentType.isFloatingPoint) {
				newline = true;

				file
				.append("\tpublic static ")
				.append(typeName(primary))
				.append(" mix_")
				.append(primary.name)
				.append('_')
				.append(primary.name)
				.append('_')
				.append(primary.name)
				.append('(')
				.append(typeName(primary))
				.append(" a, ")
				.append(typeName(primary))
				.append(" b, ")
				.append(typeName(primary))
				.append(" f) { return ");

				if (primary.shape != GroupShape.UNIT) {
					file.append("b.sub(a).mul(f).add(a); }\n");

					file
					.append("\tpublic static ")
					.append(typeName(primary))
					.append(" mix_")
					.append(primary.name)
					.append('_')
					.append(primary.name)
					.append('_')
					.append(VectorType.get(primary.componentType, GroupShape.UNIT).name)
					.append('(')
					.append(typeName(primary))
					.append(" a, ")
					.append(typeName(primary))
					.append(" b, ")
					.append(primary.componentType.holderClass(GroupShape.UNIT).getSimpleName())
					.append(" f) { return b.sub(a).mul(f).add(a); }\n");
				}
				else {
					file.append("(b - a) * f + a; }\n");
				}

				file
				.append("\tpublic static ")
				.append(typeName(primary))
				.append(" unmix_")
				.append(primary.name)
				.append('_')
				.append(primary.name)
				.append('_')
				.append(primary.name)
				.append('(')
				.append(typeName(primary))
				.append(" a, ")
				.append(typeName(primary))
				.append(" b, ")
				.append(typeName(primary))
				.append(" f) { return ");

				if (primary.shape != GroupShape.UNIT) {
					file.append("f.sub(a).div(b.sub(a)); }\n");
				}
				else {
					file.append("(f - a) / (b - a); }\n");
				}
			}
			if (newline) file.append('\n');
		}
		file.append("""
			public static int pow_int_int(int a, int b) {
				if (b <= 0) return b == 0 ? 1 : 0;
				int accum = a;
				for (int mask = Integer.MIN_VALUE >>> Integer.numberOfLeadingZeros(b); (mask >>>= 1) > 0;) {
					accum *= accum;
					if ((b & mask) != 0) accum *= a;
				}
				return accum;
			}
		
			public static long pow_long_int(long a, int b) {
				if (b <= 0) return b == 0 ? 1 : 0;
				long accum = a;
				for (int mask = Integer.MIN_VALUE >>> Integer.numberOfLeadingZeros(b); (mask >>>= 1) > 0;) {
					accum *= accum;
					if ((b & mask) != 0) accum *= a;
				}
				return accum;
			}
		
			public static float pow_float_int(float a, int b) {
				if (b <= 0) return b == 0 ? 1 : 0;
				float accum = a;
				for (int mask = Integer.MIN_VALUE >>> Integer.numberOfLeadingZeros(b); (mask >>>= 1) > 0;) {
					accum *= accum;
					if ((b & mask) != 0) accum *= a;
				}
				return accum;
			}
		
			public static double pow_double_int(double a, int b) {
				if (b <= 0) return b == 0 ? 1 : 0;
				double accum = a;
				for (int mask = Integer.MIN_VALUE >>> Integer.numberOfLeadingZeros(b); (mask >>>= 1) > 0;) {
					accum *= accum;
					if ((b & mask) != 0) accum *= a;
				}
				return accum;
			}
		}""");
		try (FileWriter writer = new FileWriter("src/main/java/builderb0y/notgimp/scripting/types/generated/VectorOperations.java")) {
			writer.write(file.toString());
		}
	}
}