package builderb0y.notgimp.scripting.types;

import jdk.incubator.vector.*;

import builderb0y.notgimp.scripting.types.VectorType.Vec;

//auto-generated by RNGGenerator.
@SuppressWarnings({ "unused" })
public class RngOperations {

	public static final long PHI64 = 0x9E3779B97F4A7C15L;

	public static long stafford(long z) {
		z = (z ^ (z >>> 30)) * 0xBF58476D1CE4E5B9L;
		z = (z ^ (z >>> 27)) * 0x94D049BB133111EBL;
		return z ^ (z >>> 31);
	}

	public static long permute_int(int salt, long seed) {
		return stafford(salt * PHI64 + seed);
	}

	public static long permute_long(long salt, long seed) {
		return stafford(salt * PHI64 + seed);
	}

	public static long permute_float(float salt, long seed) {
		return stafford(Float.floatToRawIntBits(salt) * PHI64 + seed);
	}

	public static long permute_double(double salt, long seed) {
		return stafford(Double.doubleToRawLongBits(salt) * PHI64 + seed);
	}

	public static int rng_to_positive_int(long seed) {
		return ((int)(seed)) & 0x7FFF_FFFF;
	}

	public static int rng_to_uniform_int(long seed) {
		return (int)(seed);
	}

	public static int rng_to_bounded_int(long seed, int max) {
		if (max <= 0) throw new IllegalArgumentException("bound must be positive.");

		int mask = max - 1;
		if ((max & mask) == 0) {
			return rng_to_uniform_int(seed) & mask;
		}
		else {
			while (true) {
				int bits = rng_to_positive_int(seed += PHI64);
				int result = bits % max;
				if (bits - result + mask >= 0) return result;
			}
		}
	}

	public static int rng_to_ranged_int(long seed, int min, int max) {
		return rng_to_bounded_int(seed, max - min) + min;
	}

	public static long rng_to_positive_long(long seed) {
		return seed & 0x7FFF_FFFF_FFFF_FFFFL;
	}

	public static long rng_to_uniform_long(long seed) {
		return seed;
	}

	public static long rng_to_bounded_long(long seed, long max) {
		if (max <= 0L) throw new IllegalArgumentException("bound must be positive.");
		if (max <= Integer.MAX_VALUE) return (long)(rng_to_bounded_int(seed, (int)(max)));
		long mask = max - 1;
		if ((max & mask) == 0L) {
			return rng_to_uniform_long(seed) & mask;
		}
		else {
			while (true) {
				long bits = rng_to_positive_long(seed += PHI64);
				long result = bits % max;
				if (bits - result + mask >= 0) return result;
			}
		}
	}

	public static long rng_to_ranged_long(long seed, long min, long max) {
		return rng_to_bounded_long(seed, max - min) + min;
	}

	public static float rng_to_positive_float(long seed) {
		return (seed >>> (64 - 24)) * 0x1.0p-24F;
	}

	public static float rng_to_uniform_float(long seed) {
		return (seed >> (64 - 25)) * 0x1.0p-24F;
	}

	public static float rng_to_bounded_float(long seed, float max) {
		return rng_to_positive_float(seed) * max;
	}

	public static float rng_to_ranged_float(long seed, float min, float max) {
		return rng_to_positive_float(seed) * (max - min) + min;
	}

	public static double rng_to_positive_double(long seed) {
		return (seed >>> (64 - 53)) * 0x1.0p-53D;
	}

	public static double rng_to_uniform_double(long seed) {
		return (seed >> (64 - 54)) * 0x1.0p-53D;
	}

	public static double rng_to_bounded_double(long seed, double max) {
		return rng_to_positive_double(seed) * max;
	}

	public static double rng_to_ranged_double(long seed, double min, double max) {
		return rng_to_positive_double(seed) * (max - min) + min;
	}

	public static @Vec(2) IntVector rng_to_positive_int2(long seed) { return VectorOperations.int2_from_int_int(rng_to_positive_int(permute_int(0, seed)), rng_to_positive_int(permute_int(1, seed))); }
	public static @Vec(3) IntVector rng_to_positive_int3(long seed) { return VectorOperations.int3_from_int_int_int(rng_to_positive_int(permute_int(0, seed)), rng_to_positive_int(permute_int(1, seed)), rng_to_positive_int(permute_int(2, seed))); }
	public static @Vec(4) IntVector rng_to_positive_int4(long seed) { return VectorOperations.int4_from_int_int_int_int(rng_to_positive_int(permute_int(0, seed)), rng_to_positive_int(permute_int(1, seed)), rng_to_positive_int(permute_int(2, seed)), rng_to_positive_int(permute_int(3, seed))); }
	public static @Vec(2) FloatVector rng_to_positive_float2(long seed) { return VectorOperations.float2_from_float_float(rng_to_positive_float(permute_int(0, seed)), rng_to_positive_float(permute_int(1, seed))); }
	public static @Vec(3) FloatVector rng_to_positive_float3(long seed) { return VectorOperations.float3_from_float_float_float(rng_to_positive_float(permute_int(0, seed)), rng_to_positive_float(permute_int(1, seed)), rng_to_positive_float(permute_int(2, seed))); }
	public static @Vec(4) FloatVector rng_to_positive_float4(long seed) { return VectorOperations.float4_from_float_float_float_float(rng_to_positive_float(permute_int(0, seed)), rng_to_positive_float(permute_int(1, seed)), rng_to_positive_float(permute_int(2, seed)), rng_to_positive_float(permute_int(3, seed))); }
	public static @Vec(2) LongVector rng_to_positive_long2(long seed) { return VectorOperations.long2_from_long_long(rng_to_positive_long(permute_int(0, seed)), rng_to_positive_long(permute_int(1, seed))); }
	public static @Vec(3) LongVector rng_to_positive_long3(long seed) { return VectorOperations.long3_from_long_long_long(rng_to_positive_long(permute_int(0, seed)), rng_to_positive_long(permute_int(1, seed)), rng_to_positive_long(permute_int(2, seed))); }
	public static @Vec(4) LongVector rng_to_positive_long4(long seed) { return VectorOperations.long4_from_long_long_long_long(rng_to_positive_long(permute_int(0, seed)), rng_to_positive_long(permute_int(1, seed)), rng_to_positive_long(permute_int(2, seed)), rng_to_positive_long(permute_int(3, seed))); }
	public static @Vec(2) DoubleVector rng_to_positive_double2(long seed) { return VectorOperations.double2_from_double_double(rng_to_positive_double(permute_int(0, seed)), rng_to_positive_double(permute_int(1, seed))); }
	public static @Vec(3) DoubleVector rng_to_positive_double3(long seed) { return VectorOperations.double3_from_double_double_double(rng_to_positive_double(permute_int(0, seed)), rng_to_positive_double(permute_int(1, seed)), rng_to_positive_double(permute_int(2, seed))); }
	public static @Vec(4) DoubleVector rng_to_positive_double4(long seed) { return VectorOperations.double4_from_double_double_double_double(rng_to_positive_double(permute_int(0, seed)), rng_to_positive_double(permute_int(1, seed)), rng_to_positive_double(permute_int(2, seed)), rng_to_positive_double(permute_int(3, seed))); }
	public static @Vec(2) IntVector rng_to_uniform_int2(long seed) { return VectorOperations.int2_from_int_int(rng_to_uniform_int(permute_int(0, seed)), rng_to_uniform_int(permute_int(1, seed))); }
	public static @Vec(3) IntVector rng_to_uniform_int3(long seed) { return VectorOperations.int3_from_int_int_int(rng_to_uniform_int(permute_int(0, seed)), rng_to_uniform_int(permute_int(1, seed)), rng_to_uniform_int(permute_int(2, seed))); }
	public static @Vec(4) IntVector rng_to_uniform_int4(long seed) { return VectorOperations.int4_from_int_int_int_int(rng_to_uniform_int(permute_int(0, seed)), rng_to_uniform_int(permute_int(1, seed)), rng_to_uniform_int(permute_int(2, seed)), rng_to_uniform_int(permute_int(3, seed))); }
	public static @Vec(2) FloatVector rng_to_uniform_float2(long seed) { return VectorOperations.float2_from_float_float(rng_to_uniform_float(permute_int(0, seed)), rng_to_uniform_float(permute_int(1, seed))); }
	public static @Vec(3) FloatVector rng_to_uniform_float3(long seed) { return VectorOperations.float3_from_float_float_float(rng_to_uniform_float(permute_int(0, seed)), rng_to_uniform_float(permute_int(1, seed)), rng_to_uniform_float(permute_int(2, seed))); }
	public static @Vec(4) FloatVector rng_to_uniform_float4(long seed) { return VectorOperations.float4_from_float_float_float_float(rng_to_uniform_float(permute_int(0, seed)), rng_to_uniform_float(permute_int(1, seed)), rng_to_uniform_float(permute_int(2, seed)), rng_to_uniform_float(permute_int(3, seed))); }
	public static @Vec(2) LongVector rng_to_uniform_long2(long seed) { return VectorOperations.long2_from_long_long(rng_to_uniform_long(permute_int(0, seed)), rng_to_uniform_long(permute_int(1, seed))); }
	public static @Vec(3) LongVector rng_to_uniform_long3(long seed) { return VectorOperations.long3_from_long_long_long(rng_to_uniform_long(permute_int(0, seed)), rng_to_uniform_long(permute_int(1, seed)), rng_to_uniform_long(permute_int(2, seed))); }
	public static @Vec(4) LongVector rng_to_uniform_long4(long seed) { return VectorOperations.long4_from_long_long_long_long(rng_to_uniform_long(permute_int(0, seed)), rng_to_uniform_long(permute_int(1, seed)), rng_to_uniform_long(permute_int(2, seed)), rng_to_uniform_long(permute_int(3, seed))); }
	public static @Vec(2) DoubleVector rng_to_uniform_double2(long seed) { return VectorOperations.double2_from_double_double(rng_to_uniform_double(permute_int(0, seed)), rng_to_uniform_double(permute_int(1, seed))); }
	public static @Vec(3) DoubleVector rng_to_uniform_double3(long seed) { return VectorOperations.double3_from_double_double_double(rng_to_uniform_double(permute_int(0, seed)), rng_to_uniform_double(permute_int(1, seed)), rng_to_uniform_double(permute_int(2, seed))); }
	public static @Vec(4) DoubleVector rng_to_uniform_double4(long seed) { return VectorOperations.double4_from_double_double_double_double(rng_to_uniform_double(permute_int(0, seed)), rng_to_uniform_double(permute_int(1, seed)), rng_to_uniform_double(permute_int(2, seed)), rng_to_uniform_double(permute_int(3, seed))); }
	public static @Vec(2) IntVector rng_to_bounded_int2(long seed, int max) { return VectorOperations.int2_from_int_int(rng_to_bounded_int(permute_int(0, seed), max), rng_to_bounded_int(permute_int(1, seed), max)); }
	public static @Vec(3) IntVector rng_to_bounded_int3(long seed, int max) { return VectorOperations.int3_from_int_int_int(rng_to_bounded_int(permute_int(0, seed), max), rng_to_bounded_int(permute_int(1, seed), max), rng_to_bounded_int(permute_int(2, seed), max)); }
	public static @Vec(4) IntVector rng_to_bounded_int4(long seed, int max) { return VectorOperations.int4_from_int_int_int_int(rng_to_bounded_int(permute_int(0, seed), max), rng_to_bounded_int(permute_int(1, seed), max), rng_to_bounded_int(permute_int(2, seed), max), rng_to_bounded_int(permute_int(3, seed), max)); }
	public static @Vec(2) FloatVector rng_to_bounded_float2(long seed, float max) { return VectorOperations.float2_from_float_float(rng_to_bounded_float(permute_int(0, seed), max), rng_to_bounded_float(permute_int(1, seed), max)); }
	public static @Vec(3) FloatVector rng_to_bounded_float3(long seed, float max) { return VectorOperations.float3_from_float_float_float(rng_to_bounded_float(permute_int(0, seed), max), rng_to_bounded_float(permute_int(1, seed), max), rng_to_bounded_float(permute_int(2, seed), max)); }
	public static @Vec(4) FloatVector rng_to_bounded_float4(long seed, float max) { return VectorOperations.float4_from_float_float_float_float(rng_to_bounded_float(permute_int(0, seed), max), rng_to_bounded_float(permute_int(1, seed), max), rng_to_bounded_float(permute_int(2, seed), max), rng_to_bounded_float(permute_int(3, seed), max)); }
	public static @Vec(2) LongVector rng_to_bounded_long2(long seed, long max) { return VectorOperations.long2_from_long_long(rng_to_bounded_long(permute_int(0, seed), max), rng_to_bounded_long(permute_int(1, seed), max)); }
	public static @Vec(3) LongVector rng_to_bounded_long3(long seed, long max) { return VectorOperations.long3_from_long_long_long(rng_to_bounded_long(permute_int(0, seed), max), rng_to_bounded_long(permute_int(1, seed), max), rng_to_bounded_long(permute_int(2, seed), max)); }
	public static @Vec(4) LongVector rng_to_bounded_long4(long seed, long max) { return VectorOperations.long4_from_long_long_long_long(rng_to_bounded_long(permute_int(0, seed), max), rng_to_bounded_long(permute_int(1, seed), max), rng_to_bounded_long(permute_int(2, seed), max), rng_to_bounded_long(permute_int(3, seed), max)); }
	public static @Vec(2) DoubleVector rng_to_bounded_double2(long seed, double max) { return VectorOperations.double2_from_double_double(rng_to_bounded_double(permute_int(0, seed), max), rng_to_bounded_double(permute_int(1, seed), max)); }
	public static @Vec(3) DoubleVector rng_to_bounded_double3(long seed, double max) { return VectorOperations.double3_from_double_double_double(rng_to_bounded_double(permute_int(0, seed), max), rng_to_bounded_double(permute_int(1, seed), max), rng_to_bounded_double(permute_int(2, seed), max)); }
	public static @Vec(4) DoubleVector rng_to_bounded_double4(long seed, double max) { return VectorOperations.double4_from_double_double_double_double(rng_to_bounded_double(permute_int(0, seed), max), rng_to_bounded_double(permute_int(1, seed), max), rng_to_bounded_double(permute_int(2, seed), max), rng_to_bounded_double(permute_int(3, seed), max)); }
	public static @Vec(2) IntVector rng_to_ranged_int2(long seed, int min, int max) { return VectorOperations.int2_from_int_int(rng_to_ranged_int(permute_int(0, seed), min, max), rng_to_ranged_int(permute_int(1, seed), min, max)); }
	public static @Vec(3) IntVector rng_to_ranged_int3(long seed, int min, int max) { return VectorOperations.int3_from_int_int_int(rng_to_ranged_int(permute_int(0, seed), min, max), rng_to_ranged_int(permute_int(1, seed), min, max), rng_to_ranged_int(permute_int(2, seed), min, max)); }
	public static @Vec(4) IntVector rng_to_ranged_int4(long seed, int min, int max) { return VectorOperations.int4_from_int_int_int_int(rng_to_ranged_int(permute_int(0, seed), min, max), rng_to_ranged_int(permute_int(1, seed), min, max), rng_to_ranged_int(permute_int(2, seed), min, max), rng_to_ranged_int(permute_int(3, seed), min, max)); }
	public static @Vec(2) FloatVector rng_to_ranged_float2(long seed, float min, float max) { return VectorOperations.float2_from_float_float(rng_to_ranged_float(permute_int(0, seed), min, max), rng_to_ranged_float(permute_int(1, seed), min, max)); }
	public static @Vec(3) FloatVector rng_to_ranged_float3(long seed, float min, float max) { return VectorOperations.float3_from_float_float_float(rng_to_ranged_float(permute_int(0, seed), min, max), rng_to_ranged_float(permute_int(1, seed), min, max), rng_to_ranged_float(permute_int(2, seed), min, max)); }
	public static @Vec(4) FloatVector rng_to_ranged_float4(long seed, float min, float max) { return VectorOperations.float4_from_float_float_float_float(rng_to_ranged_float(permute_int(0, seed), min, max), rng_to_ranged_float(permute_int(1, seed), min, max), rng_to_ranged_float(permute_int(2, seed), min, max), rng_to_ranged_float(permute_int(3, seed), min, max)); }
	public static @Vec(2) LongVector rng_to_ranged_long2(long seed, long min, long max) { return VectorOperations.long2_from_long_long(rng_to_ranged_long(permute_int(0, seed), min, max), rng_to_ranged_long(permute_int(1, seed), min, max)); }
	public static @Vec(3) LongVector rng_to_ranged_long3(long seed, long min, long max) { return VectorOperations.long3_from_long_long_long(rng_to_ranged_long(permute_int(0, seed), min, max), rng_to_ranged_long(permute_int(1, seed), min, max), rng_to_ranged_long(permute_int(2, seed), min, max)); }
	public static @Vec(4) LongVector rng_to_ranged_long4(long seed, long min, long max) { return VectorOperations.long4_from_long_long_long_long(rng_to_ranged_long(permute_int(0, seed), min, max), rng_to_ranged_long(permute_int(1, seed), min, max), rng_to_ranged_long(permute_int(2, seed), min, max), rng_to_ranged_long(permute_int(3, seed), min, max)); }
	public static @Vec(2) DoubleVector rng_to_ranged_double2(long seed, double min, double max) { return VectorOperations.double2_from_double_double(rng_to_ranged_double(permute_int(0, seed), min, max), rng_to_ranged_double(permute_int(1, seed), min, max)); }
	public static @Vec(3) DoubleVector rng_to_ranged_double3(long seed, double min, double max) { return VectorOperations.double3_from_double_double_double(rng_to_ranged_double(permute_int(0, seed), min, max), rng_to_ranged_double(permute_int(1, seed), min, max), rng_to_ranged_double(permute_int(2, seed), min, max)); }
	public static @Vec(4) DoubleVector rng_to_ranged_double4(long seed, double min, double max) { return VectorOperations.double4_from_double_double_double_double(rng_to_ranged_double(permute_int(0, seed), min, max), rng_to_ranged_double(permute_int(1, seed), min, max), rng_to_ranged_double(permute_int(2, seed), min, max), rng_to_ranged_double(permute_int(3, seed), min, max)); }
}