package builderb0y.notgimp.scripting.types;

import java.math.*;
import jdk.incubator.vector.*;
import builderb0y.notgimp.scripting.types.VectorType.Vec;

//auto-generated by OpsGenerator.
@SuppressWarnings({
	"unused",
	"StandardVariableNames",
	"ImplicitNumericConversion",
	"NumericCastThatLosesPrecision",
	"MethodParameterNamingConvention",
	"UnpredictableBigDecimalConstructorCall",
})
public class VectorOperations {

	public static final VectorMask<Integer> INT3_MASK = VectorMask.fromValues(IntVector.SPECIES_128, true, true, true, false);
	public static final VectorMask<Long> LONG3_MASK = VectorMask.fromValues(LongVector.SPECIES_256, true, true, true, false);
	public static final VectorMask<Float> FLOAT3_MASK = VectorMask.fromValues(FloatVector.SPECIES_128, true, true, true, false);
	public static final VectorMask<Double> DOUBLE3_MASK = VectorMask.fromValues(DoubleVector.SPECIES_256, true, true, true, false);

	public static int int_from_int(int a) { return a; }
	public static int int_from_long(long a) { return (int)a; }
	public static int int_from_float(float a) { return (int)a; }
	public static int int_from_double(double a) { return (int)a; }

	public static int neg_int(int a) { return -a; }
	public static int not_int(int a) { return ~a; }
	public static int abs_int(int a) { return Math.abs(a); }

	public static int add_int_int(int a, int b) { return a + b; }
	public static int sub_int_int(int a, int b) { return a - b; }
	public static int mul_int_int(int a, int b) { return a * b; }
	public static int div_int_int(int a, int b) { return a / b; }
	public static int and_int_int(int a, int b) { return a & b; }
	public static int or_int_int(int a, int b) { return a | b; }
	public static int xor_int_int(int a, int b) { return a ^ b; }
	public static int lshl_int_int(int a, int b) { return a << b; }
	public static int lshr_int_int(int a, int b) { return a >>> b; }
	public static int ashr_int_int(int a, int b) { return a >> b; }
	public static int min_int_int(int a, int b) { return Math.min(a, b); }
	public static int max_int_int(int a, int b) { return Math.max(a, b); }
	public static @Vec(2) IntVector add_int_int2(int a, @Vec(2) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_64, a).lanewise(VectorOperators.ADD, b); }
	public static @Vec(2) IntVector sub_int_int2(int a, @Vec(2) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_64, a).lanewise(VectorOperators.SUB, b); }
	public static @Vec(2) IntVector mul_int_int2(int a, @Vec(2) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_64, a).lanewise(VectorOperators.MUL, b); }
	public static @Vec(2) IntVector div_int_int2(int a, @Vec(2) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_64, a).lanewise(VectorOperators.DIV, b, INT3_MASK); }
	public static @Vec(2) IntVector and_int_int2(int a, @Vec(2) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_64, a).lanewise(VectorOperators.AND, b); }
	public static @Vec(2) IntVector or_int_int2(int a, @Vec(2) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_64, a).lanewise(VectorOperators.OR, b); }
	public static @Vec(2) IntVector xor_int_int2(int a, @Vec(2) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_64, a).lanewise(VectorOperators.XOR, b); }
	public static @Vec(2) IntVector lshl_int_int2(int a, @Vec(2) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_64, a).lanewise(VectorOperators.LSHL, b); }
	public static @Vec(2) IntVector lshr_int_int2(int a, @Vec(2) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_64, a).lanewise(VectorOperators.LSHR, b); }
	public static @Vec(2) IntVector ashr_int_int2(int a, @Vec(2) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_64, a).lanewise(VectorOperators.ASHR, b); }
	public static @Vec(2) IntVector min_int_int2(int a, @Vec(2) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_64, a).lanewise(VectorOperators.MIN, b); }
	public static @Vec(2) IntVector max_int_int2(int a, @Vec(2) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_64, a).lanewise(VectorOperators.MAX, b); }
	public static @Vec(3) IntVector add_int_int3(int a, @Vec(3) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_128, a).lanewise(VectorOperators.ADD, b); }
	public static @Vec(3) IntVector sub_int_int3(int a, @Vec(3) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_128, a).lanewise(VectorOperators.SUB, b); }
	public static @Vec(3) IntVector mul_int_int3(int a, @Vec(3) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_128, a).lanewise(VectorOperators.MUL, b); }
	public static @Vec(3) IntVector div_int_int3(int a, @Vec(3) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_128, a).lanewise(VectorOperators.DIV, b, INT3_MASK); }
	public static @Vec(3) IntVector and_int_int3(int a, @Vec(3) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_128, a).lanewise(VectorOperators.AND, b); }
	public static @Vec(3) IntVector or_int_int3(int a, @Vec(3) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_128, a).lanewise(VectorOperators.OR, b); }
	public static @Vec(3) IntVector xor_int_int3(int a, @Vec(3) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_128, a).lanewise(VectorOperators.XOR, b); }
	public static @Vec(3) IntVector lshl_int_int3(int a, @Vec(3) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_128, a).lanewise(VectorOperators.LSHL, b); }
	public static @Vec(3) IntVector lshr_int_int3(int a, @Vec(3) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_128, a).lanewise(VectorOperators.LSHR, b); }
	public static @Vec(3) IntVector ashr_int_int3(int a, @Vec(3) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_128, a).lanewise(VectorOperators.ASHR, b); }
	public static @Vec(3) IntVector min_int_int3(int a, @Vec(3) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_128, a).lanewise(VectorOperators.MIN, b); }
	public static @Vec(3) IntVector max_int_int3(int a, @Vec(3) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_128, a).lanewise(VectorOperators.MAX, b); }
	public static @Vec(4) IntVector add_int_int4(int a, @Vec(4) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_128, a).lanewise(VectorOperators.ADD, b); }
	public static @Vec(4) IntVector sub_int_int4(int a, @Vec(4) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_128, a).lanewise(VectorOperators.SUB, b); }
	public static @Vec(4) IntVector mul_int_int4(int a, @Vec(4) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_128, a).lanewise(VectorOperators.MUL, b); }
	public static @Vec(4) IntVector div_int_int4(int a, @Vec(4) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_128, a).lanewise(VectorOperators.DIV, b, INT3_MASK); }
	public static @Vec(4) IntVector and_int_int4(int a, @Vec(4) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_128, a).lanewise(VectorOperators.AND, b); }
	public static @Vec(4) IntVector or_int_int4(int a, @Vec(4) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_128, a).lanewise(VectorOperators.OR, b); }
	public static @Vec(4) IntVector xor_int_int4(int a, @Vec(4) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_128, a).lanewise(VectorOperators.XOR, b); }
	public static @Vec(4) IntVector lshl_int_int4(int a, @Vec(4) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_128, a).lanewise(VectorOperators.LSHL, b); }
	public static @Vec(4) IntVector lshr_int_int4(int a, @Vec(4) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_128, a).lanewise(VectorOperators.LSHR, b); }
	public static @Vec(4) IntVector ashr_int_int4(int a, @Vec(4) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_128, a).lanewise(VectorOperators.ASHR, b); }
	public static @Vec(4) IntVector min_int_int4(int a, @Vec(4) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_128, a).lanewise(VectorOperators.MIN, b); }
	public static @Vec(4) IntVector max_int_int4(int a, @Vec(4) IntVector b) { return IntVector.broadcast(IntVector.SPECIES_128, a).lanewise(VectorOperators.MAX, b); }

	public static @Vec(2) IntVector int2_from_int2(@Vec(2) IntVector a) { return a; }
	public static @Vec(2) IntVector int2_from_long2(@Vec(2) LongVector a) { return (IntVector)a.convertShape(VectorOperators.L2I, IntVector.SPECIES_64, 0); }
	public static @Vec(2) IntVector int2_from_float2(@Vec(2) FloatVector a) { return (IntVector)a.convert(VectorOperators.F2I, 0); }
	public static @Vec(2) IntVector int2_from_double2(@Vec(2) DoubleVector a) { return (IntVector)a.convertShape(VectorOperators.D2I, IntVector.SPECIES_64, 0); }
	public static @Vec(2) IntVector int2_from_int(int a) { return IntVector.broadcast(IntVector.SPECIES_64, a); }
	public static @Vec(2) IntVector int2_from_int_int(int a, int b) { return IntVector.fromArray(IntVector.SPECIES_64, new int[] { a, b }, 0); }

	public static @Vec(2) IntVector neg_int2(@Vec(2) IntVector a) { return a.lanewise(VectorOperators.NEG); }
	public static @Vec(2) IntVector not_int2(@Vec(2) IntVector a) { return a.lanewise(VectorOperators.NOT); }
	public static @Vec(2) IntVector abs_int2(@Vec(2) IntVector a) { return a.lanewise(VectorOperators.ABS); }

	public static @Vec(2) IntVector add_int2_int(@Vec(2) IntVector a, int b) { return a.lanewise(VectorOperators.ADD, b); }
	public static @Vec(2) IntVector sub_int2_int(@Vec(2) IntVector a, int b) { return a.lanewise(VectorOperators.SUB, b); }
	public static @Vec(2) IntVector mul_int2_int(@Vec(2) IntVector a, int b) { return a.lanewise(VectorOperators.MUL, b); }
	public static @Vec(2) IntVector div_int2_int(@Vec(2) IntVector a, int b) { return a.lanewise(VectorOperators.DIV, b, INT3_MASK); }
	public static @Vec(2) IntVector and_int2_int(@Vec(2) IntVector a, int b) { return a.lanewise(VectorOperators.AND, b); }
	public static @Vec(2) IntVector or_int2_int(@Vec(2) IntVector a, int b) { return a.lanewise(VectorOperators.OR, b); }
	public static @Vec(2) IntVector xor_int2_int(@Vec(2) IntVector a, int b) { return a.lanewise(VectorOperators.XOR, b); }
	public static @Vec(2) IntVector lshl_int2_int(@Vec(2) IntVector a, int b) { return a.lanewise(VectorOperators.LSHL, b); }
	public static @Vec(2) IntVector lshr_int2_int(@Vec(2) IntVector a, int b) { return a.lanewise(VectorOperators.LSHR, b); }
	public static @Vec(2) IntVector ashr_int2_int(@Vec(2) IntVector a, int b) { return a.lanewise(VectorOperators.ASHR, b); }
	public static @Vec(2) IntVector min_int2_int(@Vec(2) IntVector a, int b) { return a.lanewise(VectorOperators.MIN, b); }
	public static @Vec(2) IntVector max_int2_int(@Vec(2) IntVector a, int b) { return a.lanewise(VectorOperators.MAX, b); }
	public static @Vec(2) IntVector add_int2_int2(@Vec(2) IntVector a, @Vec(2) IntVector b) { return a.lanewise(VectorOperators.ADD, b); }
	public static @Vec(2) IntVector sub_int2_int2(@Vec(2) IntVector a, @Vec(2) IntVector b) { return a.lanewise(VectorOperators.SUB, b); }
	public static @Vec(2) IntVector mul_int2_int2(@Vec(2) IntVector a, @Vec(2) IntVector b) { return a.lanewise(VectorOperators.MUL, b); }
	public static @Vec(2) IntVector div_int2_int2(@Vec(2) IntVector a, @Vec(2) IntVector b) { return a.lanewise(VectorOperators.DIV, b, INT3_MASK); }
	public static @Vec(2) IntVector and_int2_int2(@Vec(2) IntVector a, @Vec(2) IntVector b) { return a.lanewise(VectorOperators.AND, b); }
	public static @Vec(2) IntVector or_int2_int2(@Vec(2) IntVector a, @Vec(2) IntVector b) { return a.lanewise(VectorOperators.OR, b); }
	public static @Vec(2) IntVector xor_int2_int2(@Vec(2) IntVector a, @Vec(2) IntVector b) { return a.lanewise(VectorOperators.XOR, b); }
	public static @Vec(2) IntVector lshl_int2_int2(@Vec(2) IntVector a, @Vec(2) IntVector b) { return a.lanewise(VectorOperators.LSHL, b); }
	public static @Vec(2) IntVector lshr_int2_int2(@Vec(2) IntVector a, @Vec(2) IntVector b) { return a.lanewise(VectorOperators.LSHR, b); }
	public static @Vec(2) IntVector ashr_int2_int2(@Vec(2) IntVector a, @Vec(2) IntVector b) { return a.lanewise(VectorOperators.ASHR, b); }
	public static @Vec(2) IntVector min_int2_int2(@Vec(2) IntVector a, @Vec(2) IntVector b) { return a.lanewise(VectorOperators.MIN, b); }
	public static @Vec(2) IntVector max_int2_int2(@Vec(2) IntVector a, @Vec(2) IntVector b) { return a.lanewise(VectorOperators.MAX, b); }

	public static int dot_int2_int2(@Vec(2) IntVector a, @Vec(2) IntVector b) { return a.mul(b).reduceLanes(VectorOperators.ADD); }
	public static int lengthSquared_int2(@Vec(2) IntVector a) { return dot_int2_int2(a, a); }

	public static @Vec(3) IntVector int3_from_int3(@Vec(3) IntVector a) { return a; }
	public static @Vec(3) IntVector int3_from_long3(@Vec(3) LongVector a) { return (IntVector)a.convertShape(VectorOperators.L2I, IntVector.SPECIES_128, 0); }
	public static @Vec(3) IntVector int3_from_float3(@Vec(3) FloatVector a) { return (IntVector)a.convert(VectorOperators.F2I, 0); }
	public static @Vec(3) IntVector int3_from_double3(@Vec(3) DoubleVector a) { return (IntVector)a.convertShape(VectorOperators.D2I, IntVector.SPECIES_128, 0); }
	public static @Vec(3) IntVector int3_from_int(int a) { return IntVector.broadcast(IntVector.SPECIES_128, a); }
	public static @Vec(3) IntVector int3_from_int_int_int(int a, int b, int c) { return IntVector.fromArray(IntVector.SPECIES_128, new int[] { a, b, c, 0 }, 0); }

	public static @Vec(3) IntVector neg_int3(@Vec(3) IntVector a) { return a.lanewise(VectorOperators.NEG); }
	public static @Vec(3) IntVector not_int3(@Vec(3) IntVector a) { return a.lanewise(VectorOperators.NOT); }
	public static @Vec(3) IntVector abs_int3(@Vec(3) IntVector a) { return a.lanewise(VectorOperators.ABS); }

	public static @Vec(3) IntVector add_int3_int(@Vec(3) IntVector a, int b) { return a.lanewise(VectorOperators.ADD, b); }
	public static @Vec(3) IntVector sub_int3_int(@Vec(3) IntVector a, int b) { return a.lanewise(VectorOperators.SUB, b); }
	public static @Vec(3) IntVector mul_int3_int(@Vec(3) IntVector a, int b) { return a.lanewise(VectorOperators.MUL, b); }
	public static @Vec(3) IntVector div_int3_int(@Vec(3) IntVector a, int b) { return a.lanewise(VectorOperators.DIV, b, INT3_MASK); }
	public static @Vec(3) IntVector and_int3_int(@Vec(3) IntVector a, int b) { return a.lanewise(VectorOperators.AND, b); }
	public static @Vec(3) IntVector or_int3_int(@Vec(3) IntVector a, int b) { return a.lanewise(VectorOperators.OR, b); }
	public static @Vec(3) IntVector xor_int3_int(@Vec(3) IntVector a, int b) { return a.lanewise(VectorOperators.XOR, b); }
	public static @Vec(3) IntVector lshl_int3_int(@Vec(3) IntVector a, int b) { return a.lanewise(VectorOperators.LSHL, b); }
	public static @Vec(3) IntVector lshr_int3_int(@Vec(3) IntVector a, int b) { return a.lanewise(VectorOperators.LSHR, b); }
	public static @Vec(3) IntVector ashr_int3_int(@Vec(3) IntVector a, int b) { return a.lanewise(VectorOperators.ASHR, b); }
	public static @Vec(3) IntVector min_int3_int(@Vec(3) IntVector a, int b) { return a.lanewise(VectorOperators.MIN, b); }
	public static @Vec(3) IntVector max_int3_int(@Vec(3) IntVector a, int b) { return a.lanewise(VectorOperators.MAX, b); }
	public static @Vec(3) IntVector add_int3_int3(@Vec(3) IntVector a, @Vec(3) IntVector b) { return a.lanewise(VectorOperators.ADD, b); }
	public static @Vec(3) IntVector sub_int3_int3(@Vec(3) IntVector a, @Vec(3) IntVector b) { return a.lanewise(VectorOperators.SUB, b); }
	public static @Vec(3) IntVector mul_int3_int3(@Vec(3) IntVector a, @Vec(3) IntVector b) { return a.lanewise(VectorOperators.MUL, b); }
	public static @Vec(3) IntVector div_int3_int3(@Vec(3) IntVector a, @Vec(3) IntVector b) { return a.lanewise(VectorOperators.DIV, b, INT3_MASK); }
	public static @Vec(3) IntVector and_int3_int3(@Vec(3) IntVector a, @Vec(3) IntVector b) { return a.lanewise(VectorOperators.AND, b); }
	public static @Vec(3) IntVector or_int3_int3(@Vec(3) IntVector a, @Vec(3) IntVector b) { return a.lanewise(VectorOperators.OR, b); }
	public static @Vec(3) IntVector xor_int3_int3(@Vec(3) IntVector a, @Vec(3) IntVector b) { return a.lanewise(VectorOperators.XOR, b); }
	public static @Vec(3) IntVector lshl_int3_int3(@Vec(3) IntVector a, @Vec(3) IntVector b) { return a.lanewise(VectorOperators.LSHL, b); }
	public static @Vec(3) IntVector lshr_int3_int3(@Vec(3) IntVector a, @Vec(3) IntVector b) { return a.lanewise(VectorOperators.LSHR, b); }
	public static @Vec(3) IntVector ashr_int3_int3(@Vec(3) IntVector a, @Vec(3) IntVector b) { return a.lanewise(VectorOperators.ASHR, b); }
	public static @Vec(3) IntVector min_int3_int3(@Vec(3) IntVector a, @Vec(3) IntVector b) { return a.lanewise(VectorOperators.MIN, b); }
	public static @Vec(3) IntVector max_int3_int3(@Vec(3) IntVector a, @Vec(3) IntVector b) { return a.lanewise(VectorOperators.MAX, b); }

	public static int dot_int3_int3(@Vec(3) IntVector a, @Vec(3) IntVector b) { return a.mul(b).reduceLanes(VectorOperators.ADD); }
	public static int lengthSquared_int3(@Vec(3) IntVector a) { return dot_int3_int3(a, a); }

	public static @Vec(4) IntVector int4_from_int4(@Vec(4) IntVector a) { return a; }
	public static @Vec(4) IntVector int4_from_long4(@Vec(4) LongVector a) { return (IntVector)a.convertShape(VectorOperators.L2I, IntVector.SPECIES_128, 0); }
	public static @Vec(4) IntVector int4_from_float4(@Vec(4) FloatVector a) { return (IntVector)a.convert(VectorOperators.F2I, 0); }
	public static @Vec(4) IntVector int4_from_double4(@Vec(4) DoubleVector a) { return (IntVector)a.convertShape(VectorOperators.D2I, IntVector.SPECIES_128, 0); }
	public static @Vec(4) IntVector int4_from_int(int a) { return IntVector.broadcast(IntVector.SPECIES_128, a); }
	public static @Vec(4) IntVector int4_from_int_int_int_int(int a, int b, int c, int d) { return IntVector.fromArray(IntVector.SPECIES_128, new int[] { a, b, c, d }, 0); }

	public static @Vec(4) IntVector neg_int4(@Vec(4) IntVector a) { return a.lanewise(VectorOperators.NEG); }
	public static @Vec(4) IntVector not_int4(@Vec(4) IntVector a) { return a.lanewise(VectorOperators.NOT); }
	public static @Vec(4) IntVector abs_int4(@Vec(4) IntVector a) { return a.lanewise(VectorOperators.ABS); }

	public static @Vec(4) IntVector add_int4_int(@Vec(4) IntVector a, int b) { return a.lanewise(VectorOperators.ADD, b); }
	public static @Vec(4) IntVector sub_int4_int(@Vec(4) IntVector a, int b) { return a.lanewise(VectorOperators.SUB, b); }
	public static @Vec(4) IntVector mul_int4_int(@Vec(4) IntVector a, int b) { return a.lanewise(VectorOperators.MUL, b); }
	public static @Vec(4) IntVector div_int4_int(@Vec(4) IntVector a, int b) { return a.lanewise(VectorOperators.DIV, b, INT3_MASK); }
	public static @Vec(4) IntVector and_int4_int(@Vec(4) IntVector a, int b) { return a.lanewise(VectorOperators.AND, b); }
	public static @Vec(4) IntVector or_int4_int(@Vec(4) IntVector a, int b) { return a.lanewise(VectorOperators.OR, b); }
	public static @Vec(4) IntVector xor_int4_int(@Vec(4) IntVector a, int b) { return a.lanewise(VectorOperators.XOR, b); }
	public static @Vec(4) IntVector lshl_int4_int(@Vec(4) IntVector a, int b) { return a.lanewise(VectorOperators.LSHL, b); }
	public static @Vec(4) IntVector lshr_int4_int(@Vec(4) IntVector a, int b) { return a.lanewise(VectorOperators.LSHR, b); }
	public static @Vec(4) IntVector ashr_int4_int(@Vec(4) IntVector a, int b) { return a.lanewise(VectorOperators.ASHR, b); }
	public static @Vec(4) IntVector min_int4_int(@Vec(4) IntVector a, int b) { return a.lanewise(VectorOperators.MIN, b); }
	public static @Vec(4) IntVector max_int4_int(@Vec(4) IntVector a, int b) { return a.lanewise(VectorOperators.MAX, b); }
	public static @Vec(4) IntVector add_int4_int4(@Vec(4) IntVector a, @Vec(4) IntVector b) { return a.lanewise(VectorOperators.ADD, b); }
	public static @Vec(4) IntVector sub_int4_int4(@Vec(4) IntVector a, @Vec(4) IntVector b) { return a.lanewise(VectorOperators.SUB, b); }
	public static @Vec(4) IntVector mul_int4_int4(@Vec(4) IntVector a, @Vec(4) IntVector b) { return a.lanewise(VectorOperators.MUL, b); }
	public static @Vec(4) IntVector div_int4_int4(@Vec(4) IntVector a, @Vec(4) IntVector b) { return a.lanewise(VectorOperators.DIV, b, INT3_MASK); }
	public static @Vec(4) IntVector and_int4_int4(@Vec(4) IntVector a, @Vec(4) IntVector b) { return a.lanewise(VectorOperators.AND, b); }
	public static @Vec(4) IntVector or_int4_int4(@Vec(4) IntVector a, @Vec(4) IntVector b) { return a.lanewise(VectorOperators.OR, b); }
	public static @Vec(4) IntVector xor_int4_int4(@Vec(4) IntVector a, @Vec(4) IntVector b) { return a.lanewise(VectorOperators.XOR, b); }
	public static @Vec(4) IntVector lshl_int4_int4(@Vec(4) IntVector a, @Vec(4) IntVector b) { return a.lanewise(VectorOperators.LSHL, b); }
	public static @Vec(4) IntVector lshr_int4_int4(@Vec(4) IntVector a, @Vec(4) IntVector b) { return a.lanewise(VectorOperators.LSHR, b); }
	public static @Vec(4) IntVector ashr_int4_int4(@Vec(4) IntVector a, @Vec(4) IntVector b) { return a.lanewise(VectorOperators.ASHR, b); }
	public static @Vec(4) IntVector min_int4_int4(@Vec(4) IntVector a, @Vec(4) IntVector b) { return a.lanewise(VectorOperators.MIN, b); }
	public static @Vec(4) IntVector max_int4_int4(@Vec(4) IntVector a, @Vec(4) IntVector b) { return a.lanewise(VectorOperators.MAX, b); }

	public static int dot_int4_int4(@Vec(4) IntVector a, @Vec(4) IntVector b) { return a.mul(b).reduceLanes(VectorOperators.ADD); }
	public static int lengthSquared_int4(@Vec(4) IntVector a) { return dot_int4_int4(a, a); }

	public static long long_from_int(int a) { return (long)a; }
	public static long long_from_long(long a) { return a; }
	public static long long_from_float(float a) { return (long)a; }
	public static long long_from_double(double a) { return (long)a; }

	public static long neg_long(long a) { return -a; }
	public static long not_long(long a) { return ~a; }
	public static long abs_long(long a) { return Math.abs(a); }

	public static long add_long_long(long a, long b) { return a + b; }
	public static long sub_long_long(long a, long b) { return a - b; }
	public static long mul_long_long(long a, long b) { return a * b; }
	public static long div_long_long(long a, long b) { return a / b; }
	public static long and_long_long(long a, long b) { return a & b; }
	public static long or_long_long(long a, long b) { return a | b; }
	public static long xor_long_long(long a, long b) { return a ^ b; }
	public static long lshl_long_long(long a, long b) { return a << b; }
	public static long lshr_long_long(long a, long b) { return a >>> b; }
	public static long ashr_long_long(long a, long b) { return a >> b; }
	public static long min_long_long(long a, long b) { return Math.min(a, b); }
	public static long max_long_long(long a, long b) { return Math.max(a, b); }
	public static @Vec(2) LongVector add_long_long2(long a, @Vec(2) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_128, a).lanewise(VectorOperators.ADD, b); }
	public static @Vec(2) LongVector sub_long_long2(long a, @Vec(2) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_128, a).lanewise(VectorOperators.SUB, b); }
	public static @Vec(2) LongVector mul_long_long2(long a, @Vec(2) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_128, a).lanewise(VectorOperators.MUL, b); }
	public static @Vec(2) LongVector div_long_long2(long a, @Vec(2) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_128, a).lanewise(VectorOperators.DIV, b, LONG3_MASK); }
	public static @Vec(2) LongVector and_long_long2(long a, @Vec(2) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_128, a).lanewise(VectorOperators.AND, b); }
	public static @Vec(2) LongVector or_long_long2(long a, @Vec(2) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_128, a).lanewise(VectorOperators.OR, b); }
	public static @Vec(2) LongVector xor_long_long2(long a, @Vec(2) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_128, a).lanewise(VectorOperators.XOR, b); }
	public static @Vec(2) LongVector lshl_long_long2(long a, @Vec(2) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_128, a).lanewise(VectorOperators.LSHL, b); }
	public static @Vec(2) LongVector lshr_long_long2(long a, @Vec(2) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_128, a).lanewise(VectorOperators.LSHR, b); }
	public static @Vec(2) LongVector ashr_long_long2(long a, @Vec(2) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_128, a).lanewise(VectorOperators.ASHR, b); }
	public static @Vec(2) LongVector min_long_long2(long a, @Vec(2) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_128, a).lanewise(VectorOperators.MIN, b); }
	public static @Vec(2) LongVector max_long_long2(long a, @Vec(2) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_128, a).lanewise(VectorOperators.MAX, b); }
	public static @Vec(3) LongVector add_long_long3(long a, @Vec(3) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_256, a).lanewise(VectorOperators.ADD, b); }
	public static @Vec(3) LongVector sub_long_long3(long a, @Vec(3) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_256, a).lanewise(VectorOperators.SUB, b); }
	public static @Vec(3) LongVector mul_long_long3(long a, @Vec(3) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_256, a).lanewise(VectorOperators.MUL, b); }
	public static @Vec(3) LongVector div_long_long3(long a, @Vec(3) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_256, a).lanewise(VectorOperators.DIV, b, LONG3_MASK); }
	public static @Vec(3) LongVector and_long_long3(long a, @Vec(3) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_256, a).lanewise(VectorOperators.AND, b); }
	public static @Vec(3) LongVector or_long_long3(long a, @Vec(3) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_256, a).lanewise(VectorOperators.OR, b); }
	public static @Vec(3) LongVector xor_long_long3(long a, @Vec(3) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_256, a).lanewise(VectorOperators.XOR, b); }
	public static @Vec(3) LongVector lshl_long_long3(long a, @Vec(3) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_256, a).lanewise(VectorOperators.LSHL, b); }
	public static @Vec(3) LongVector lshr_long_long3(long a, @Vec(3) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_256, a).lanewise(VectorOperators.LSHR, b); }
	public static @Vec(3) LongVector ashr_long_long3(long a, @Vec(3) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_256, a).lanewise(VectorOperators.ASHR, b); }
	public static @Vec(3) LongVector min_long_long3(long a, @Vec(3) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_256, a).lanewise(VectorOperators.MIN, b); }
	public static @Vec(3) LongVector max_long_long3(long a, @Vec(3) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_256, a).lanewise(VectorOperators.MAX, b); }
	public static @Vec(4) LongVector add_long_long4(long a, @Vec(4) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_256, a).lanewise(VectorOperators.ADD, b); }
	public static @Vec(4) LongVector sub_long_long4(long a, @Vec(4) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_256, a).lanewise(VectorOperators.SUB, b); }
	public static @Vec(4) LongVector mul_long_long4(long a, @Vec(4) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_256, a).lanewise(VectorOperators.MUL, b); }
	public static @Vec(4) LongVector div_long_long4(long a, @Vec(4) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_256, a).lanewise(VectorOperators.DIV, b, LONG3_MASK); }
	public static @Vec(4) LongVector and_long_long4(long a, @Vec(4) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_256, a).lanewise(VectorOperators.AND, b); }
	public static @Vec(4) LongVector or_long_long4(long a, @Vec(4) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_256, a).lanewise(VectorOperators.OR, b); }
	public static @Vec(4) LongVector xor_long_long4(long a, @Vec(4) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_256, a).lanewise(VectorOperators.XOR, b); }
	public static @Vec(4) LongVector lshl_long_long4(long a, @Vec(4) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_256, a).lanewise(VectorOperators.LSHL, b); }
	public static @Vec(4) LongVector lshr_long_long4(long a, @Vec(4) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_256, a).lanewise(VectorOperators.LSHR, b); }
	public static @Vec(4) LongVector ashr_long_long4(long a, @Vec(4) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_256, a).lanewise(VectorOperators.ASHR, b); }
	public static @Vec(4) LongVector min_long_long4(long a, @Vec(4) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_256, a).lanewise(VectorOperators.MIN, b); }
	public static @Vec(4) LongVector max_long_long4(long a, @Vec(4) LongVector b) { return LongVector.broadcast(LongVector.SPECIES_256, a).lanewise(VectorOperators.MAX, b); }

	public static @Vec(2) LongVector long2_from_int2(@Vec(2) IntVector a) { return (LongVector)a.convertShape(VectorOperators.I2L, LongVector.SPECIES_128, 0); }
	public static @Vec(2) LongVector long2_from_long2(@Vec(2) LongVector a) { return a; }
	public static @Vec(2) LongVector long2_from_float2(@Vec(2) FloatVector a) { return (LongVector)a.convertShape(VectorOperators.F2L, LongVector.SPECIES_128, 0); }
	public static @Vec(2) LongVector long2_from_double2(@Vec(2) DoubleVector a) { return (LongVector)a.convert(VectorOperators.D2L, 0); }
	public static @Vec(2) LongVector long2_from_long(long a) { return LongVector.broadcast(LongVector.SPECIES_128, a); }
	public static @Vec(2) LongVector long2_from_long_long(long a, long b) { return LongVector.fromArray(LongVector.SPECIES_128, new long[] { a, b }, 0); }

	public static @Vec(2) LongVector neg_long2(@Vec(2) LongVector a) { return a.lanewise(VectorOperators.NEG); }
	public static @Vec(2) LongVector not_long2(@Vec(2) LongVector a) { return a.lanewise(VectorOperators.NOT); }
	public static @Vec(2) LongVector abs_long2(@Vec(2) LongVector a) { return a.lanewise(VectorOperators.ABS); }

	public static @Vec(2) LongVector add_long2_long(@Vec(2) LongVector a, long b) { return a.lanewise(VectorOperators.ADD, b); }
	public static @Vec(2) LongVector sub_long2_long(@Vec(2) LongVector a, long b) { return a.lanewise(VectorOperators.SUB, b); }
	public static @Vec(2) LongVector mul_long2_long(@Vec(2) LongVector a, long b) { return a.lanewise(VectorOperators.MUL, b); }
	public static @Vec(2) LongVector div_long2_long(@Vec(2) LongVector a, long b) { return a.lanewise(VectorOperators.DIV, b, LONG3_MASK); }
	public static @Vec(2) LongVector and_long2_long(@Vec(2) LongVector a, long b) { return a.lanewise(VectorOperators.AND, b); }
	public static @Vec(2) LongVector or_long2_long(@Vec(2) LongVector a, long b) { return a.lanewise(VectorOperators.OR, b); }
	public static @Vec(2) LongVector xor_long2_long(@Vec(2) LongVector a, long b) { return a.lanewise(VectorOperators.XOR, b); }
	public static @Vec(2) LongVector lshl_long2_long(@Vec(2) LongVector a, long b) { return a.lanewise(VectorOperators.LSHL, b); }
	public static @Vec(2) LongVector lshr_long2_long(@Vec(2) LongVector a, long b) { return a.lanewise(VectorOperators.LSHR, b); }
	public static @Vec(2) LongVector ashr_long2_long(@Vec(2) LongVector a, long b) { return a.lanewise(VectorOperators.ASHR, b); }
	public static @Vec(2) LongVector min_long2_long(@Vec(2) LongVector a, long b) { return a.lanewise(VectorOperators.MIN, b); }
	public static @Vec(2) LongVector max_long2_long(@Vec(2) LongVector a, long b) { return a.lanewise(VectorOperators.MAX, b); }
	public static @Vec(2) LongVector add_long2_long2(@Vec(2) LongVector a, @Vec(2) LongVector b) { return a.lanewise(VectorOperators.ADD, b); }
	public static @Vec(2) LongVector sub_long2_long2(@Vec(2) LongVector a, @Vec(2) LongVector b) { return a.lanewise(VectorOperators.SUB, b); }
	public static @Vec(2) LongVector mul_long2_long2(@Vec(2) LongVector a, @Vec(2) LongVector b) { return a.lanewise(VectorOperators.MUL, b); }
	public static @Vec(2) LongVector div_long2_long2(@Vec(2) LongVector a, @Vec(2) LongVector b) { return a.lanewise(VectorOperators.DIV, b, LONG3_MASK); }
	public static @Vec(2) LongVector and_long2_long2(@Vec(2) LongVector a, @Vec(2) LongVector b) { return a.lanewise(VectorOperators.AND, b); }
	public static @Vec(2) LongVector or_long2_long2(@Vec(2) LongVector a, @Vec(2) LongVector b) { return a.lanewise(VectorOperators.OR, b); }
	public static @Vec(2) LongVector xor_long2_long2(@Vec(2) LongVector a, @Vec(2) LongVector b) { return a.lanewise(VectorOperators.XOR, b); }
	public static @Vec(2) LongVector lshl_long2_long2(@Vec(2) LongVector a, @Vec(2) LongVector b) { return a.lanewise(VectorOperators.LSHL, b); }
	public static @Vec(2) LongVector lshr_long2_long2(@Vec(2) LongVector a, @Vec(2) LongVector b) { return a.lanewise(VectorOperators.LSHR, b); }
	public static @Vec(2) LongVector ashr_long2_long2(@Vec(2) LongVector a, @Vec(2) LongVector b) { return a.lanewise(VectorOperators.ASHR, b); }
	public static @Vec(2) LongVector min_long2_long2(@Vec(2) LongVector a, @Vec(2) LongVector b) { return a.lanewise(VectorOperators.MIN, b); }
	public static @Vec(2) LongVector max_long2_long2(@Vec(2) LongVector a, @Vec(2) LongVector b) { return a.lanewise(VectorOperators.MAX, b); }

	public static long dot_long2_long2(@Vec(2) LongVector a, @Vec(2) LongVector b) { return a.mul(b).reduceLanes(VectorOperators.ADD); }
	public static long lengthSquared_long2(@Vec(2) LongVector a) { return dot_long2_long2(a, a); }

	public static @Vec(3) LongVector long3_from_int3(@Vec(3) IntVector a) { return (LongVector)a.convertShape(VectorOperators.I2L, LongVector.SPECIES_256, 0); }
	public static @Vec(3) LongVector long3_from_long3(@Vec(3) LongVector a) { return a; }
	public static @Vec(3) LongVector long3_from_float3(@Vec(3) FloatVector a) { return (LongVector)a.convertShape(VectorOperators.F2L, LongVector.SPECIES_256, 0); }
	public static @Vec(3) LongVector long3_from_double3(@Vec(3) DoubleVector a) { return (LongVector)a.convert(VectorOperators.D2L, 0); }
	public static @Vec(3) LongVector long3_from_long(long a) { return LongVector.broadcast(LongVector.SPECIES_256, a); }
	public static @Vec(3) LongVector long3_from_long_long_long(long a, long b, long c) { return LongVector.fromArray(LongVector.SPECIES_256, new long[] { a, b, c, 0 }, 0); }

	public static @Vec(3) LongVector neg_long3(@Vec(3) LongVector a) { return a.lanewise(VectorOperators.NEG); }
	public static @Vec(3) LongVector not_long3(@Vec(3) LongVector a) { return a.lanewise(VectorOperators.NOT); }
	public static @Vec(3) LongVector abs_long3(@Vec(3) LongVector a) { return a.lanewise(VectorOperators.ABS); }

	public static @Vec(3) LongVector add_long3_long(@Vec(3) LongVector a, long b) { return a.lanewise(VectorOperators.ADD, b); }
	public static @Vec(3) LongVector sub_long3_long(@Vec(3) LongVector a, long b) { return a.lanewise(VectorOperators.SUB, b); }
	public static @Vec(3) LongVector mul_long3_long(@Vec(3) LongVector a, long b) { return a.lanewise(VectorOperators.MUL, b); }
	public static @Vec(3) LongVector div_long3_long(@Vec(3) LongVector a, long b) { return a.lanewise(VectorOperators.DIV, b, LONG3_MASK); }
	public static @Vec(3) LongVector and_long3_long(@Vec(3) LongVector a, long b) { return a.lanewise(VectorOperators.AND, b); }
	public static @Vec(3) LongVector or_long3_long(@Vec(3) LongVector a, long b) { return a.lanewise(VectorOperators.OR, b); }
	public static @Vec(3) LongVector xor_long3_long(@Vec(3) LongVector a, long b) { return a.lanewise(VectorOperators.XOR, b); }
	public static @Vec(3) LongVector lshl_long3_long(@Vec(3) LongVector a, long b) { return a.lanewise(VectorOperators.LSHL, b); }
	public static @Vec(3) LongVector lshr_long3_long(@Vec(3) LongVector a, long b) { return a.lanewise(VectorOperators.LSHR, b); }
	public static @Vec(3) LongVector ashr_long3_long(@Vec(3) LongVector a, long b) { return a.lanewise(VectorOperators.ASHR, b); }
	public static @Vec(3) LongVector min_long3_long(@Vec(3) LongVector a, long b) { return a.lanewise(VectorOperators.MIN, b); }
	public static @Vec(3) LongVector max_long3_long(@Vec(3) LongVector a, long b) { return a.lanewise(VectorOperators.MAX, b); }
	public static @Vec(3) LongVector add_long3_long3(@Vec(3) LongVector a, @Vec(3) LongVector b) { return a.lanewise(VectorOperators.ADD, b); }
	public static @Vec(3) LongVector sub_long3_long3(@Vec(3) LongVector a, @Vec(3) LongVector b) { return a.lanewise(VectorOperators.SUB, b); }
	public static @Vec(3) LongVector mul_long3_long3(@Vec(3) LongVector a, @Vec(3) LongVector b) { return a.lanewise(VectorOperators.MUL, b); }
	public static @Vec(3) LongVector div_long3_long3(@Vec(3) LongVector a, @Vec(3) LongVector b) { return a.lanewise(VectorOperators.DIV, b, LONG3_MASK); }
	public static @Vec(3) LongVector and_long3_long3(@Vec(3) LongVector a, @Vec(3) LongVector b) { return a.lanewise(VectorOperators.AND, b); }
	public static @Vec(3) LongVector or_long3_long3(@Vec(3) LongVector a, @Vec(3) LongVector b) { return a.lanewise(VectorOperators.OR, b); }
	public static @Vec(3) LongVector xor_long3_long3(@Vec(3) LongVector a, @Vec(3) LongVector b) { return a.lanewise(VectorOperators.XOR, b); }
	public static @Vec(3) LongVector lshl_long3_long3(@Vec(3) LongVector a, @Vec(3) LongVector b) { return a.lanewise(VectorOperators.LSHL, b); }
	public static @Vec(3) LongVector lshr_long3_long3(@Vec(3) LongVector a, @Vec(3) LongVector b) { return a.lanewise(VectorOperators.LSHR, b); }
	public static @Vec(3) LongVector ashr_long3_long3(@Vec(3) LongVector a, @Vec(3) LongVector b) { return a.lanewise(VectorOperators.ASHR, b); }
	public static @Vec(3) LongVector min_long3_long3(@Vec(3) LongVector a, @Vec(3) LongVector b) { return a.lanewise(VectorOperators.MIN, b); }
	public static @Vec(3) LongVector max_long3_long3(@Vec(3) LongVector a, @Vec(3) LongVector b) { return a.lanewise(VectorOperators.MAX, b); }

	public static long dot_long3_long3(@Vec(3) LongVector a, @Vec(3) LongVector b) { return a.mul(b).reduceLanes(VectorOperators.ADD); }
	public static long lengthSquared_long3(@Vec(3) LongVector a) { return dot_long3_long3(a, a); }

	public static @Vec(4) LongVector long4_from_int4(@Vec(4) IntVector a) { return (LongVector)a.convertShape(VectorOperators.I2L, LongVector.SPECIES_256, 0); }
	public static @Vec(4) LongVector long4_from_long4(@Vec(4) LongVector a) { return a; }
	public static @Vec(4) LongVector long4_from_float4(@Vec(4) FloatVector a) { return (LongVector)a.convertShape(VectorOperators.F2L, LongVector.SPECIES_256, 0); }
	public static @Vec(4) LongVector long4_from_double4(@Vec(4) DoubleVector a) { return (LongVector)a.convert(VectorOperators.D2L, 0); }
	public static @Vec(4) LongVector long4_from_long(long a) { return LongVector.broadcast(LongVector.SPECIES_256, a); }
	public static @Vec(4) LongVector long4_from_long_long_long_long(long a, long b, long c, long d) { return LongVector.fromArray(LongVector.SPECIES_256, new long[] { a, b, c, d }, 0); }

	public static @Vec(4) LongVector neg_long4(@Vec(4) LongVector a) { return a.lanewise(VectorOperators.NEG); }
	public static @Vec(4) LongVector not_long4(@Vec(4) LongVector a) { return a.lanewise(VectorOperators.NOT); }
	public static @Vec(4) LongVector abs_long4(@Vec(4) LongVector a) { return a.lanewise(VectorOperators.ABS); }

	public static @Vec(4) LongVector add_long4_long(@Vec(4) LongVector a, long b) { return a.lanewise(VectorOperators.ADD, b); }
	public static @Vec(4) LongVector sub_long4_long(@Vec(4) LongVector a, long b) { return a.lanewise(VectorOperators.SUB, b); }
	public static @Vec(4) LongVector mul_long4_long(@Vec(4) LongVector a, long b) { return a.lanewise(VectorOperators.MUL, b); }
	public static @Vec(4) LongVector div_long4_long(@Vec(4) LongVector a, long b) { return a.lanewise(VectorOperators.DIV, b, LONG3_MASK); }
	public static @Vec(4) LongVector and_long4_long(@Vec(4) LongVector a, long b) { return a.lanewise(VectorOperators.AND, b); }
	public static @Vec(4) LongVector or_long4_long(@Vec(4) LongVector a, long b) { return a.lanewise(VectorOperators.OR, b); }
	public static @Vec(4) LongVector xor_long4_long(@Vec(4) LongVector a, long b) { return a.lanewise(VectorOperators.XOR, b); }
	public static @Vec(4) LongVector lshl_long4_long(@Vec(4) LongVector a, long b) { return a.lanewise(VectorOperators.LSHL, b); }
	public static @Vec(4) LongVector lshr_long4_long(@Vec(4) LongVector a, long b) { return a.lanewise(VectorOperators.LSHR, b); }
	public static @Vec(4) LongVector ashr_long4_long(@Vec(4) LongVector a, long b) { return a.lanewise(VectorOperators.ASHR, b); }
	public static @Vec(4) LongVector min_long4_long(@Vec(4) LongVector a, long b) { return a.lanewise(VectorOperators.MIN, b); }
	public static @Vec(4) LongVector max_long4_long(@Vec(4) LongVector a, long b) { return a.lanewise(VectorOperators.MAX, b); }
	public static @Vec(4) LongVector add_long4_long4(@Vec(4) LongVector a, @Vec(4) LongVector b) { return a.lanewise(VectorOperators.ADD, b); }
	public static @Vec(4) LongVector sub_long4_long4(@Vec(4) LongVector a, @Vec(4) LongVector b) { return a.lanewise(VectorOperators.SUB, b); }
	public static @Vec(4) LongVector mul_long4_long4(@Vec(4) LongVector a, @Vec(4) LongVector b) { return a.lanewise(VectorOperators.MUL, b); }
	public static @Vec(4) LongVector div_long4_long4(@Vec(4) LongVector a, @Vec(4) LongVector b) { return a.lanewise(VectorOperators.DIV, b, LONG3_MASK); }
	public static @Vec(4) LongVector and_long4_long4(@Vec(4) LongVector a, @Vec(4) LongVector b) { return a.lanewise(VectorOperators.AND, b); }
	public static @Vec(4) LongVector or_long4_long4(@Vec(4) LongVector a, @Vec(4) LongVector b) { return a.lanewise(VectorOperators.OR, b); }
	public static @Vec(4) LongVector xor_long4_long4(@Vec(4) LongVector a, @Vec(4) LongVector b) { return a.lanewise(VectorOperators.XOR, b); }
	public static @Vec(4) LongVector lshl_long4_long4(@Vec(4) LongVector a, @Vec(4) LongVector b) { return a.lanewise(VectorOperators.LSHL, b); }
	public static @Vec(4) LongVector lshr_long4_long4(@Vec(4) LongVector a, @Vec(4) LongVector b) { return a.lanewise(VectorOperators.LSHR, b); }
	public static @Vec(4) LongVector ashr_long4_long4(@Vec(4) LongVector a, @Vec(4) LongVector b) { return a.lanewise(VectorOperators.ASHR, b); }
	public static @Vec(4) LongVector min_long4_long4(@Vec(4) LongVector a, @Vec(4) LongVector b) { return a.lanewise(VectorOperators.MIN, b); }
	public static @Vec(4) LongVector max_long4_long4(@Vec(4) LongVector a, @Vec(4) LongVector b) { return a.lanewise(VectorOperators.MAX, b); }

	public static long dot_long4_long4(@Vec(4) LongVector a, @Vec(4) LongVector b) { return a.mul(b).reduceLanes(VectorOperators.ADD); }
	public static long lengthSquared_long4(@Vec(4) LongVector a) { return dot_long4_long4(a, a); }

	public static float float_from_int(int a) { return (float)a; }
	public static float float_from_long(long a) { return (float)a; }
	public static float float_from_float(float a) { return a; }
	public static float float_from_double(double a) { return (float)a; }

	public static float neg_float(float a) { return -a; }
	public static float abs_float(float a) { return Math.abs(a); }
	public static float sin_float(float a) { return (float)Math.sin(a); }
	public static float cos_float(float a) { return (float)Math.cos(a); }
	public static float tan_float(float a) { return (float)Math.tan(a); }
	public static float asin_float(float a) { return (float)Math.asin(a); }
	public static float acos_float(float a) { return (float)Math.acos(a); }
	public static float atan_float(float a) { return (float)Math.atan(a); }
	public static float sinh_float(float a) { return (float)Math.sinh(a); }
	public static float cosh_float(float a) { return (float)Math.cosh(a); }
	public static float tanh_float(float a) { return (float)Math.tanh(a); }
	public static float sqrt_float(float a) { return (float)Math.sqrt(a); }
	public static float cbrt_float(float a) { return (float)Math.cbrt(a); }
	public static float exp_float(float a) { return (float)Math.exp(a); }
	public static float log_float(float a) { return (float)Math.log(a); }

	public static float add_float_float(float a, float b) { return a + b; }
	public static float sub_float_float(float a, float b) { return a - b; }
	public static float mul_float_float(float a, float b) { return a * b; }
	public static float div_float_float(float a, float b) { return a / b; }
	public static float pow_float_float(float a, float b) { return (float)Math.pow(a, b); }
	public static float atan2_float_float(float a, float b) { return (float)Math.atan2(b, a); }
	public static float min_float_float(float a, float b) { return Math.min(a, b); }
	public static float max_float_float(float a, float b) { return Math.max(a, b); }
	public static @Vec(2) FloatVector add_float_float2(float a, @Vec(2) FloatVector b) { return FloatVector.broadcast(FloatVector.SPECIES_64, a).lanewise(VectorOperators.ADD, b); }
	public static @Vec(2) FloatVector sub_float_float2(float a, @Vec(2) FloatVector b) { return FloatVector.broadcast(FloatVector.SPECIES_64, a).lanewise(VectorOperators.SUB, b); }
	public static @Vec(2) FloatVector mul_float_float2(float a, @Vec(2) FloatVector b) { return FloatVector.broadcast(FloatVector.SPECIES_64, a).lanewise(VectorOperators.MUL, b); }
	public static @Vec(2) FloatVector div_float_float2(float a, @Vec(2) FloatVector b) { return FloatVector.broadcast(FloatVector.SPECIES_64, a).lanewise(VectorOperators.DIV, b); }
	public static @Vec(2) FloatVector pow_float_float2(float a, @Vec(2) FloatVector b) { return FloatVector.broadcast(FloatVector.SPECIES_64, a).lanewise(VectorOperators.POW, b); }
	public static @Vec(2) FloatVector atan2_float_float2(float a, @Vec(2) FloatVector b) { return FloatVector.broadcast(FloatVector.SPECIES_64, a).lanewise(VectorOperators.ATAN2, b); }
	public static @Vec(2) FloatVector min_float_float2(float a, @Vec(2) FloatVector b) { return FloatVector.broadcast(FloatVector.SPECIES_64, a).lanewise(VectorOperators.MIN, b); }
	public static @Vec(2) FloatVector max_float_float2(float a, @Vec(2) FloatVector b) { return FloatVector.broadcast(FloatVector.SPECIES_64, a).lanewise(VectorOperators.MAX, b); }
	public static @Vec(3) FloatVector add_float_float3(float a, @Vec(3) FloatVector b) { return FloatVector.broadcast(FloatVector.SPECIES_128, a).lanewise(VectorOperators.ADD, b); }
	public static @Vec(3) FloatVector sub_float_float3(float a, @Vec(3) FloatVector b) { return FloatVector.broadcast(FloatVector.SPECIES_128, a).lanewise(VectorOperators.SUB, b); }
	public static @Vec(3) FloatVector mul_float_float3(float a, @Vec(3) FloatVector b) { return FloatVector.broadcast(FloatVector.SPECIES_128, a).lanewise(VectorOperators.MUL, b); }
	public static @Vec(3) FloatVector div_float_float3(float a, @Vec(3) FloatVector b) { return FloatVector.broadcast(FloatVector.SPECIES_128, a).lanewise(VectorOperators.DIV, b); }
	public static @Vec(3) FloatVector pow_float_float3(float a, @Vec(3) FloatVector b) { return FloatVector.broadcast(FloatVector.SPECIES_128, a).lanewise(VectorOperators.POW, b); }
	public static @Vec(3) FloatVector atan2_float_float3(float a, @Vec(3) FloatVector b) { return FloatVector.broadcast(FloatVector.SPECIES_128, a).lanewise(VectorOperators.ATAN2, b); }
	public static @Vec(3) FloatVector min_float_float3(float a, @Vec(3) FloatVector b) { return FloatVector.broadcast(FloatVector.SPECIES_128, a).lanewise(VectorOperators.MIN, b); }
	public static @Vec(3) FloatVector max_float_float3(float a, @Vec(3) FloatVector b) { return FloatVector.broadcast(FloatVector.SPECIES_128, a).lanewise(VectorOperators.MAX, b); }
	public static @Vec(4) FloatVector add_float_float4(float a, @Vec(4) FloatVector b) { return FloatVector.broadcast(FloatVector.SPECIES_128, a).lanewise(VectorOperators.ADD, b); }
	public static @Vec(4) FloatVector sub_float_float4(float a, @Vec(4) FloatVector b) { return FloatVector.broadcast(FloatVector.SPECIES_128, a).lanewise(VectorOperators.SUB, b); }
	public static @Vec(4) FloatVector mul_float_float4(float a, @Vec(4) FloatVector b) { return FloatVector.broadcast(FloatVector.SPECIES_128, a).lanewise(VectorOperators.MUL, b); }
	public static @Vec(4) FloatVector div_float_float4(float a, @Vec(4) FloatVector b) { return FloatVector.broadcast(FloatVector.SPECIES_128, a).lanewise(VectorOperators.DIV, b); }
	public static @Vec(4) FloatVector pow_float_float4(float a, @Vec(4) FloatVector b) { return FloatVector.broadcast(FloatVector.SPECIES_128, a).lanewise(VectorOperators.POW, b); }
	public static @Vec(4) FloatVector atan2_float_float4(float a, @Vec(4) FloatVector b) { return FloatVector.broadcast(FloatVector.SPECIES_128, a).lanewise(VectorOperators.ATAN2, b); }
	public static @Vec(4) FloatVector min_float_float4(float a, @Vec(4) FloatVector b) { return FloatVector.broadcast(FloatVector.SPECIES_128, a).lanewise(VectorOperators.MIN, b); }
	public static @Vec(4) FloatVector max_float_float4(float a, @Vec(4) FloatVector b) { return FloatVector.broadcast(FloatVector.SPECIES_128, a).lanewise(VectorOperators.MAX, b); }

	public static float mix_float_float_float(float a, float b, float f) { return (b - a) * f + a; }

	public static @Vec(2) FloatVector float2_from_int2(@Vec(2) IntVector a) { return (FloatVector)a.convert(VectorOperators.I2F, 0); }
	public static @Vec(2) FloatVector float2_from_long2(@Vec(2) LongVector a) { return (FloatVector)a.convertShape(VectorOperators.L2F, FloatVector.SPECIES_64, 0); }
	public static @Vec(2) FloatVector float2_from_float2(@Vec(2) FloatVector a) { return a; }
	public static @Vec(2) FloatVector float2_from_double2(@Vec(2) DoubleVector a) { return (FloatVector)a.convertShape(VectorOperators.D2F, FloatVector.SPECIES_64, 0); }
	public static @Vec(2) FloatVector float2_from_float(float a) { return FloatVector.broadcast(FloatVector.SPECIES_64, a); }
	public static @Vec(2) FloatVector float2_from_float_float(float a, float b) { return FloatVector.fromArray(FloatVector.SPECIES_64, new float[] { a, b }, 0); }

	public static @Vec(2) FloatVector neg_float2(@Vec(2) FloatVector a) { return a.lanewise(VectorOperators.NEG); }
	public static @Vec(2) FloatVector abs_float2(@Vec(2) FloatVector a) { return a.lanewise(VectorOperators.ABS); }
	public static @Vec(2) FloatVector sin_float2(@Vec(2) FloatVector a) { return a.lanewise(VectorOperators.SIN); }
	public static @Vec(2) FloatVector cos_float2(@Vec(2) FloatVector a) { return a.lanewise(VectorOperators.COS); }
	public static @Vec(2) FloatVector tan_float2(@Vec(2) FloatVector a) { return a.lanewise(VectorOperators.TAN); }
	public static @Vec(2) FloatVector asin_float2(@Vec(2) FloatVector a) { return a.lanewise(VectorOperators.ASIN); }
	public static @Vec(2) FloatVector acos_float2(@Vec(2) FloatVector a) { return a.lanewise(VectorOperators.ACOS); }
	public static @Vec(2) FloatVector atan_float2(@Vec(2) FloatVector a) { return a.lanewise(VectorOperators.ATAN); }
	public static @Vec(2) FloatVector sinh_float2(@Vec(2) FloatVector a) { return a.lanewise(VectorOperators.SINH); }
	public static @Vec(2) FloatVector cosh_float2(@Vec(2) FloatVector a) { return a.lanewise(VectorOperators.COSH); }
	public static @Vec(2) FloatVector tanh_float2(@Vec(2) FloatVector a) { return a.lanewise(VectorOperators.TANH); }
	public static @Vec(2) FloatVector sqrt_float2(@Vec(2) FloatVector a) { return a.lanewise(VectorOperators.SQRT); }
	public static @Vec(2) FloatVector cbrt_float2(@Vec(2) FloatVector a) { return a.lanewise(VectorOperators.CBRT); }
	public static @Vec(2) FloatVector exp_float2(@Vec(2) FloatVector a) { return a.lanewise(VectorOperators.EXP); }
	public static @Vec(2) FloatVector log_float2(@Vec(2) FloatVector a) { return a.lanewise(VectorOperators.LOG); }

	public static @Vec(2) FloatVector add_float2_float(@Vec(2) FloatVector a, float b) { return a.lanewise(VectorOperators.ADD, b); }
	public static @Vec(2) FloatVector sub_float2_float(@Vec(2) FloatVector a, float b) { return a.lanewise(VectorOperators.SUB, b); }
	public static @Vec(2) FloatVector mul_float2_float(@Vec(2) FloatVector a, float b) { return a.lanewise(VectorOperators.MUL, b); }
	public static @Vec(2) FloatVector div_float2_float(@Vec(2) FloatVector a, float b) { return a.lanewise(VectorOperators.DIV, b); }
	public static @Vec(2) FloatVector pow_float2_float(@Vec(2) FloatVector a, float b) { return a.lanewise(VectorOperators.POW, b); }
	public static @Vec(2) FloatVector atan2_float2_float(@Vec(2) FloatVector a, float b) { return a.lanewise(VectorOperators.ATAN2, b); }
	public static @Vec(2) FloatVector min_float2_float(@Vec(2) FloatVector a, float b) { return a.lanewise(VectorOperators.MIN, b); }
	public static @Vec(2) FloatVector max_float2_float(@Vec(2) FloatVector a, float b) { return a.lanewise(VectorOperators.MAX, b); }
	public static @Vec(2) FloatVector add_float2_float2(@Vec(2) FloatVector a, @Vec(2) FloatVector b) { return a.lanewise(VectorOperators.ADD, b); }
	public static @Vec(2) FloatVector sub_float2_float2(@Vec(2) FloatVector a, @Vec(2) FloatVector b) { return a.lanewise(VectorOperators.SUB, b); }
	public static @Vec(2) FloatVector mul_float2_float2(@Vec(2) FloatVector a, @Vec(2) FloatVector b) { return a.lanewise(VectorOperators.MUL, b); }
	public static @Vec(2) FloatVector div_float2_float2(@Vec(2) FloatVector a, @Vec(2) FloatVector b) { return a.lanewise(VectorOperators.DIV, b); }
	public static @Vec(2) FloatVector pow_float2_float2(@Vec(2) FloatVector a, @Vec(2) FloatVector b) { return a.lanewise(VectorOperators.POW, b); }
	public static @Vec(2) FloatVector atan2_float2_float2(@Vec(2) FloatVector a, @Vec(2) FloatVector b) { return a.lanewise(VectorOperators.ATAN2, b); }
	public static @Vec(2) FloatVector min_float2_float2(@Vec(2) FloatVector a, @Vec(2) FloatVector b) { return a.lanewise(VectorOperators.MIN, b); }
	public static @Vec(2) FloatVector max_float2_float2(@Vec(2) FloatVector a, @Vec(2) FloatVector b) { return a.lanewise(VectorOperators.MAX, b); }

	public static float dot_float2_float2(@Vec(2) FloatVector a, @Vec(2) FloatVector b) { return a.mul(b).reduceLanes(VectorOperators.ADD); }
	public static float lengthSquared_float2(@Vec(2) FloatVector a) { return dot_float2_float2(a, a); }
	public static float length_float2(@Vec(2) FloatVector a) { return (float)Math.sqrt(dot_float2_float2(a, a)); }
	public static @Vec(2) FloatVector normalize_float2(@Vec(2) FloatVector a) { return a.div(length_float2(a)); }
	public static @Vec(2) FloatVector mix_float2_float2_float2(@Vec(2) FloatVector a, @Vec(2) FloatVector b, @Vec(2) FloatVector f) { return b.sub(a).mul(f).add(a); }
	public static @Vec(2) FloatVector mix_float2_float2_float(@Vec(2) FloatVector a, @Vec(2) FloatVector b, float f) { return b.sub(a).mul(f).add(a); }

	public static @Vec(3) FloatVector float3_from_int3(@Vec(3) IntVector a) { return (FloatVector)a.convert(VectorOperators.I2F, 0); }
	public static @Vec(3) FloatVector float3_from_long3(@Vec(3) LongVector a) { return (FloatVector)a.convertShape(VectorOperators.L2F, FloatVector.SPECIES_128, 0); }
	public static @Vec(3) FloatVector float3_from_float3(@Vec(3) FloatVector a) { return a; }
	public static @Vec(3) FloatVector float3_from_double3(@Vec(3) DoubleVector a) { return (FloatVector)a.convertShape(VectorOperators.D2F, FloatVector.SPECIES_128, 0); }
	public static @Vec(3) FloatVector float3_from_float(float a) { return FloatVector.broadcast(FloatVector.SPECIES_128, a); }
	public static @Vec(3) FloatVector float3_from_float_float_float(float a, float b, float c) { return FloatVector.fromArray(FloatVector.SPECIES_128, new float[] { a, b, c, 0 }, 0); }

	public static @Vec(3) FloatVector neg_float3(@Vec(3) FloatVector a) { return a.lanewise(VectorOperators.NEG); }
	public static @Vec(3) FloatVector abs_float3(@Vec(3) FloatVector a) { return a.lanewise(VectorOperators.ABS); }
	public static @Vec(3) FloatVector sin_float3(@Vec(3) FloatVector a) { return a.lanewise(VectorOperators.SIN); }
	public static @Vec(3) FloatVector cos_float3(@Vec(3) FloatVector a) { return a.lanewise(VectorOperators.COS); }
	public static @Vec(3) FloatVector tan_float3(@Vec(3) FloatVector a) { return a.lanewise(VectorOperators.TAN); }
	public static @Vec(3) FloatVector asin_float3(@Vec(3) FloatVector a) { return a.lanewise(VectorOperators.ASIN); }
	public static @Vec(3) FloatVector acos_float3(@Vec(3) FloatVector a) { return a.lanewise(VectorOperators.ACOS); }
	public static @Vec(3) FloatVector atan_float3(@Vec(3) FloatVector a) { return a.lanewise(VectorOperators.ATAN); }
	public static @Vec(3) FloatVector sinh_float3(@Vec(3) FloatVector a) { return a.lanewise(VectorOperators.SINH); }
	public static @Vec(3) FloatVector cosh_float3(@Vec(3) FloatVector a) { return a.lanewise(VectorOperators.COSH); }
	public static @Vec(3) FloatVector tanh_float3(@Vec(3) FloatVector a) { return a.lanewise(VectorOperators.TANH); }
	public static @Vec(3) FloatVector sqrt_float3(@Vec(3) FloatVector a) { return a.lanewise(VectorOperators.SQRT); }
	public static @Vec(3) FloatVector cbrt_float3(@Vec(3) FloatVector a) { return a.lanewise(VectorOperators.CBRT); }
	public static @Vec(3) FloatVector exp_float3(@Vec(3) FloatVector a) { return a.lanewise(VectorOperators.EXP); }
	public static @Vec(3) FloatVector log_float3(@Vec(3) FloatVector a) { return a.lanewise(VectorOperators.LOG); }

	public static @Vec(3) FloatVector add_float3_float(@Vec(3) FloatVector a, float b) { return a.lanewise(VectorOperators.ADD, b); }
	public static @Vec(3) FloatVector sub_float3_float(@Vec(3) FloatVector a, float b) { return a.lanewise(VectorOperators.SUB, b); }
	public static @Vec(3) FloatVector mul_float3_float(@Vec(3) FloatVector a, float b) { return a.lanewise(VectorOperators.MUL, b); }
	public static @Vec(3) FloatVector div_float3_float(@Vec(3) FloatVector a, float b) { return a.lanewise(VectorOperators.DIV, b); }
	public static @Vec(3) FloatVector pow_float3_float(@Vec(3) FloatVector a, float b) { return a.lanewise(VectorOperators.POW, b); }
	public static @Vec(3) FloatVector atan2_float3_float(@Vec(3) FloatVector a, float b) { return a.lanewise(VectorOperators.ATAN2, b); }
	public static @Vec(3) FloatVector min_float3_float(@Vec(3) FloatVector a, float b) { return a.lanewise(VectorOperators.MIN, b); }
	public static @Vec(3) FloatVector max_float3_float(@Vec(3) FloatVector a, float b) { return a.lanewise(VectorOperators.MAX, b); }
	public static @Vec(3) FloatVector add_float3_float3(@Vec(3) FloatVector a, @Vec(3) FloatVector b) { return a.lanewise(VectorOperators.ADD, b); }
	public static @Vec(3) FloatVector sub_float3_float3(@Vec(3) FloatVector a, @Vec(3) FloatVector b) { return a.lanewise(VectorOperators.SUB, b); }
	public static @Vec(3) FloatVector mul_float3_float3(@Vec(3) FloatVector a, @Vec(3) FloatVector b) { return a.lanewise(VectorOperators.MUL, b); }
	public static @Vec(3) FloatVector div_float3_float3(@Vec(3) FloatVector a, @Vec(3) FloatVector b) { return a.lanewise(VectorOperators.DIV, b); }
	public static @Vec(3) FloatVector pow_float3_float3(@Vec(3) FloatVector a, @Vec(3) FloatVector b) { return a.lanewise(VectorOperators.POW, b); }
	public static @Vec(3) FloatVector atan2_float3_float3(@Vec(3) FloatVector a, @Vec(3) FloatVector b) { return a.lanewise(VectorOperators.ATAN2, b); }
	public static @Vec(3) FloatVector min_float3_float3(@Vec(3) FloatVector a, @Vec(3) FloatVector b) { return a.lanewise(VectorOperators.MIN, b); }
	public static @Vec(3) FloatVector max_float3_float3(@Vec(3) FloatVector a, @Vec(3) FloatVector b) { return a.lanewise(VectorOperators.MAX, b); }

	public static float dot_float3_float3(@Vec(3) FloatVector a, @Vec(3) FloatVector b) { return a.mul(b).reduceLanes(VectorOperators.ADD); }
	public static float lengthSquared_float3(@Vec(3) FloatVector a) { return dot_float3_float3(a, a); }
	public static float length_float3(@Vec(3) FloatVector a) { return (float)Math.sqrt(dot_float3_float3(a, a)); }
	public static @Vec(3) FloatVector normalize_float3(@Vec(3) FloatVector a) { return a.div(length_float3(a)); }
	public static @Vec(3) FloatVector mix_float3_float3_float3(@Vec(3) FloatVector a, @Vec(3) FloatVector b, @Vec(3) FloatVector f) { return b.sub(a).mul(f).add(a); }
	public static @Vec(3) FloatVector mix_float3_float3_float(@Vec(3) FloatVector a, @Vec(3) FloatVector b, float f) { return b.sub(a).mul(f).add(a); }

	public static @Vec(4) FloatVector float4_from_int4(@Vec(4) IntVector a) { return (FloatVector)a.convert(VectorOperators.I2F, 0); }
	public static @Vec(4) FloatVector float4_from_long4(@Vec(4) LongVector a) { return (FloatVector)a.convertShape(VectorOperators.L2F, FloatVector.SPECIES_128, 0); }
	public static @Vec(4) FloatVector float4_from_float4(@Vec(4) FloatVector a) { return a; }
	public static @Vec(4) FloatVector float4_from_double4(@Vec(4) DoubleVector a) { return (FloatVector)a.convertShape(VectorOperators.D2F, FloatVector.SPECIES_128, 0); }
	public static @Vec(4) FloatVector float4_from_float(float a) { return FloatVector.broadcast(FloatVector.SPECIES_128, a); }
	public static @Vec(4) FloatVector float4_from_float_float_float_float(float a, float b, float c, float d) { return FloatVector.fromArray(FloatVector.SPECIES_128, new float[] { a, b, c, d }, 0); }

	public static @Vec(4) FloatVector neg_float4(@Vec(4) FloatVector a) { return a.lanewise(VectorOperators.NEG); }
	public static @Vec(4) FloatVector abs_float4(@Vec(4) FloatVector a) { return a.lanewise(VectorOperators.ABS); }
	public static @Vec(4) FloatVector sin_float4(@Vec(4) FloatVector a) { return a.lanewise(VectorOperators.SIN); }
	public static @Vec(4) FloatVector cos_float4(@Vec(4) FloatVector a) { return a.lanewise(VectorOperators.COS); }
	public static @Vec(4) FloatVector tan_float4(@Vec(4) FloatVector a) { return a.lanewise(VectorOperators.TAN); }
	public static @Vec(4) FloatVector asin_float4(@Vec(4) FloatVector a) { return a.lanewise(VectorOperators.ASIN); }
	public static @Vec(4) FloatVector acos_float4(@Vec(4) FloatVector a) { return a.lanewise(VectorOperators.ACOS); }
	public static @Vec(4) FloatVector atan_float4(@Vec(4) FloatVector a) { return a.lanewise(VectorOperators.ATAN); }
	public static @Vec(4) FloatVector sinh_float4(@Vec(4) FloatVector a) { return a.lanewise(VectorOperators.SINH); }
	public static @Vec(4) FloatVector cosh_float4(@Vec(4) FloatVector a) { return a.lanewise(VectorOperators.COSH); }
	public static @Vec(4) FloatVector tanh_float4(@Vec(4) FloatVector a) { return a.lanewise(VectorOperators.TANH); }
	public static @Vec(4) FloatVector sqrt_float4(@Vec(4) FloatVector a) { return a.lanewise(VectorOperators.SQRT); }
	public static @Vec(4) FloatVector cbrt_float4(@Vec(4) FloatVector a) { return a.lanewise(VectorOperators.CBRT); }
	public static @Vec(4) FloatVector exp_float4(@Vec(4) FloatVector a) { return a.lanewise(VectorOperators.EXP); }
	public static @Vec(4) FloatVector log_float4(@Vec(4) FloatVector a) { return a.lanewise(VectorOperators.LOG); }

	public static @Vec(4) FloatVector add_float4_float(@Vec(4) FloatVector a, float b) { return a.lanewise(VectorOperators.ADD, b); }
	public static @Vec(4) FloatVector sub_float4_float(@Vec(4) FloatVector a, float b) { return a.lanewise(VectorOperators.SUB, b); }
	public static @Vec(4) FloatVector mul_float4_float(@Vec(4) FloatVector a, float b) { return a.lanewise(VectorOperators.MUL, b); }
	public static @Vec(4) FloatVector div_float4_float(@Vec(4) FloatVector a, float b) { return a.lanewise(VectorOperators.DIV, b); }
	public static @Vec(4) FloatVector pow_float4_float(@Vec(4) FloatVector a, float b) { return a.lanewise(VectorOperators.POW, b); }
	public static @Vec(4) FloatVector atan2_float4_float(@Vec(4) FloatVector a, float b) { return a.lanewise(VectorOperators.ATAN2, b); }
	public static @Vec(4) FloatVector min_float4_float(@Vec(4) FloatVector a, float b) { return a.lanewise(VectorOperators.MIN, b); }
	public static @Vec(4) FloatVector max_float4_float(@Vec(4) FloatVector a, float b) { return a.lanewise(VectorOperators.MAX, b); }
	public static @Vec(4) FloatVector add_float4_float4(@Vec(4) FloatVector a, @Vec(4) FloatVector b) { return a.lanewise(VectorOperators.ADD, b); }
	public static @Vec(4) FloatVector sub_float4_float4(@Vec(4) FloatVector a, @Vec(4) FloatVector b) { return a.lanewise(VectorOperators.SUB, b); }
	public static @Vec(4) FloatVector mul_float4_float4(@Vec(4) FloatVector a, @Vec(4) FloatVector b) { return a.lanewise(VectorOperators.MUL, b); }
	public static @Vec(4) FloatVector div_float4_float4(@Vec(4) FloatVector a, @Vec(4) FloatVector b) { return a.lanewise(VectorOperators.DIV, b); }
	public static @Vec(4) FloatVector pow_float4_float4(@Vec(4) FloatVector a, @Vec(4) FloatVector b) { return a.lanewise(VectorOperators.POW, b); }
	public static @Vec(4) FloatVector atan2_float4_float4(@Vec(4) FloatVector a, @Vec(4) FloatVector b) { return a.lanewise(VectorOperators.ATAN2, b); }
	public static @Vec(4) FloatVector min_float4_float4(@Vec(4) FloatVector a, @Vec(4) FloatVector b) { return a.lanewise(VectorOperators.MIN, b); }
	public static @Vec(4) FloatVector max_float4_float4(@Vec(4) FloatVector a, @Vec(4) FloatVector b) { return a.lanewise(VectorOperators.MAX, b); }

	public static float dot_float4_float4(@Vec(4) FloatVector a, @Vec(4) FloatVector b) { return a.mul(b).reduceLanes(VectorOperators.ADD); }
	public static float lengthSquared_float4(@Vec(4) FloatVector a) { return dot_float4_float4(a, a); }
	public static float length_float4(@Vec(4) FloatVector a) { return (float)Math.sqrt(dot_float4_float4(a, a)); }
	public static @Vec(4) FloatVector normalize_float4(@Vec(4) FloatVector a) { return a.div(length_float4(a)); }
	public static @Vec(4) FloatVector mix_float4_float4_float4(@Vec(4) FloatVector a, @Vec(4) FloatVector b, @Vec(4) FloatVector f) { return b.sub(a).mul(f).add(a); }
	public static @Vec(4) FloatVector mix_float4_float4_float(@Vec(4) FloatVector a, @Vec(4) FloatVector b, float f) { return b.sub(a).mul(f).add(a); }

	public static double double_from_int(int a) { return (double)a; }
	public static double double_from_long(long a) { return (double)a; }
	public static double double_from_float(float a) { return (double)a; }
	public static double double_from_double(double a) { return a; }

	public static double neg_double(double a) { return -a; }
	public static double abs_double(double a) { return Math.abs(a); }
	public static double sin_double(double a) { return Math.sin(a); }
	public static double cos_double(double a) { return Math.cos(a); }
	public static double tan_double(double a) { return Math.tan(a); }
	public static double asin_double(double a) { return Math.asin(a); }
	public static double acos_double(double a) { return Math.acos(a); }
	public static double atan_double(double a) { return Math.atan(a); }
	public static double sinh_double(double a) { return Math.sinh(a); }
	public static double cosh_double(double a) { return Math.cosh(a); }
	public static double tanh_double(double a) { return Math.tanh(a); }
	public static double sqrt_double(double a) { return Math.sqrt(a); }
	public static double cbrt_double(double a) { return Math.cbrt(a); }
	public static double exp_double(double a) { return Math.exp(a); }
	public static double log_double(double a) { return Math.log(a); }

	public static double add_double_double(double a, double b) { return a + b; }
	public static double sub_double_double(double a, double b) { return a - b; }
	public static double mul_double_double(double a, double b) { return a * b; }
	public static double div_double_double(double a, double b) { return a / b; }
	public static double pow_double_double(double a, double b) { return Math.pow(a, b); }
	public static double atan2_double_double(double a, double b) { return Math.atan2(b, a); }
	public static double min_double_double(double a, double b) { return Math.min(a, b); }
	public static double max_double_double(double a, double b) { return Math.max(a, b); }
	public static @Vec(2) DoubleVector add_double_double2(double a, @Vec(2) DoubleVector b) { return DoubleVector.broadcast(DoubleVector.SPECIES_128, a).lanewise(VectorOperators.ADD, b); }
	public static @Vec(2) DoubleVector sub_double_double2(double a, @Vec(2) DoubleVector b) { return DoubleVector.broadcast(DoubleVector.SPECIES_128, a).lanewise(VectorOperators.SUB, b); }
	public static @Vec(2) DoubleVector mul_double_double2(double a, @Vec(2) DoubleVector b) { return DoubleVector.broadcast(DoubleVector.SPECIES_128, a).lanewise(VectorOperators.MUL, b); }
	public static @Vec(2) DoubleVector div_double_double2(double a, @Vec(2) DoubleVector b) { return DoubleVector.broadcast(DoubleVector.SPECIES_128, a).lanewise(VectorOperators.DIV, b); }
	public static @Vec(2) DoubleVector pow_double_double2(double a, @Vec(2) DoubleVector b) { return DoubleVector.broadcast(DoubleVector.SPECIES_128, a).lanewise(VectorOperators.POW, b); }
	public static @Vec(2) DoubleVector atan2_double_double2(double a, @Vec(2) DoubleVector b) { return DoubleVector.broadcast(DoubleVector.SPECIES_128, a).lanewise(VectorOperators.ATAN2, b); }
	public static @Vec(2) DoubleVector min_double_double2(double a, @Vec(2) DoubleVector b) { return DoubleVector.broadcast(DoubleVector.SPECIES_128, a).lanewise(VectorOperators.MIN, b); }
	public static @Vec(2) DoubleVector max_double_double2(double a, @Vec(2) DoubleVector b) { return DoubleVector.broadcast(DoubleVector.SPECIES_128, a).lanewise(VectorOperators.MAX, b); }
	public static @Vec(3) DoubleVector add_double_double3(double a, @Vec(3) DoubleVector b) { return DoubleVector.broadcast(DoubleVector.SPECIES_256, a).lanewise(VectorOperators.ADD, b); }
	public static @Vec(3) DoubleVector sub_double_double3(double a, @Vec(3) DoubleVector b) { return DoubleVector.broadcast(DoubleVector.SPECIES_256, a).lanewise(VectorOperators.SUB, b); }
	public static @Vec(3) DoubleVector mul_double_double3(double a, @Vec(3) DoubleVector b) { return DoubleVector.broadcast(DoubleVector.SPECIES_256, a).lanewise(VectorOperators.MUL, b); }
	public static @Vec(3) DoubleVector div_double_double3(double a, @Vec(3) DoubleVector b) { return DoubleVector.broadcast(DoubleVector.SPECIES_256, a).lanewise(VectorOperators.DIV, b); }
	public static @Vec(3) DoubleVector pow_double_double3(double a, @Vec(3) DoubleVector b) { return DoubleVector.broadcast(DoubleVector.SPECIES_256, a).lanewise(VectorOperators.POW, b); }
	public static @Vec(3) DoubleVector atan2_double_double3(double a, @Vec(3) DoubleVector b) { return DoubleVector.broadcast(DoubleVector.SPECIES_256, a).lanewise(VectorOperators.ATAN2, b); }
	public static @Vec(3) DoubleVector min_double_double3(double a, @Vec(3) DoubleVector b) { return DoubleVector.broadcast(DoubleVector.SPECIES_256, a).lanewise(VectorOperators.MIN, b); }
	public static @Vec(3) DoubleVector max_double_double3(double a, @Vec(3) DoubleVector b) { return DoubleVector.broadcast(DoubleVector.SPECIES_256, a).lanewise(VectorOperators.MAX, b); }
	public static @Vec(4) DoubleVector add_double_double4(double a, @Vec(4) DoubleVector b) { return DoubleVector.broadcast(DoubleVector.SPECIES_256, a).lanewise(VectorOperators.ADD, b); }
	public static @Vec(4) DoubleVector sub_double_double4(double a, @Vec(4) DoubleVector b) { return DoubleVector.broadcast(DoubleVector.SPECIES_256, a).lanewise(VectorOperators.SUB, b); }
	public static @Vec(4) DoubleVector mul_double_double4(double a, @Vec(4) DoubleVector b) { return DoubleVector.broadcast(DoubleVector.SPECIES_256, a).lanewise(VectorOperators.MUL, b); }
	public static @Vec(4) DoubleVector div_double_double4(double a, @Vec(4) DoubleVector b) { return DoubleVector.broadcast(DoubleVector.SPECIES_256, a).lanewise(VectorOperators.DIV, b); }
	public static @Vec(4) DoubleVector pow_double_double4(double a, @Vec(4) DoubleVector b) { return DoubleVector.broadcast(DoubleVector.SPECIES_256, a).lanewise(VectorOperators.POW, b); }
	public static @Vec(4) DoubleVector atan2_double_double4(double a, @Vec(4) DoubleVector b) { return DoubleVector.broadcast(DoubleVector.SPECIES_256, a).lanewise(VectorOperators.ATAN2, b); }
	public static @Vec(4) DoubleVector min_double_double4(double a, @Vec(4) DoubleVector b) { return DoubleVector.broadcast(DoubleVector.SPECIES_256, a).lanewise(VectorOperators.MIN, b); }
	public static @Vec(4) DoubleVector max_double_double4(double a, @Vec(4) DoubleVector b) { return DoubleVector.broadcast(DoubleVector.SPECIES_256, a).lanewise(VectorOperators.MAX, b); }

	public static double mix_double_double_double(double a, double b, double f) { return (b - a) * f + a; }

	public static @Vec(2) DoubleVector double2_from_int2(@Vec(2) IntVector a) { return (DoubleVector)a.convertShape(VectorOperators.I2D, DoubleVector.SPECIES_128, 0); }
	public static @Vec(2) DoubleVector double2_from_long2(@Vec(2) LongVector a) { return (DoubleVector)a.convert(VectorOperators.L2D, 0); }
	public static @Vec(2) DoubleVector double2_from_float2(@Vec(2) FloatVector a) { return (DoubleVector)a.convertShape(VectorOperators.F2D, DoubleVector.SPECIES_128, 0); }
	public static @Vec(2) DoubleVector double2_from_double2(@Vec(2) DoubleVector a) { return a; }
	public static @Vec(2) DoubleVector double2_from_double(double a) { return DoubleVector.broadcast(DoubleVector.SPECIES_128, a); }
	public static @Vec(2) DoubleVector double2_from_double_double(double a, double b) { return DoubleVector.fromArray(DoubleVector.SPECIES_128, new double[] { a, b }, 0); }

	public static @Vec(2) DoubleVector neg_double2(@Vec(2) DoubleVector a) { return a.lanewise(VectorOperators.NEG); }
	public static @Vec(2) DoubleVector abs_double2(@Vec(2) DoubleVector a) { return a.lanewise(VectorOperators.ABS); }
	public static @Vec(2) DoubleVector sin_double2(@Vec(2) DoubleVector a) { return a.lanewise(VectorOperators.SIN); }
	public static @Vec(2) DoubleVector cos_double2(@Vec(2) DoubleVector a) { return a.lanewise(VectorOperators.COS); }
	public static @Vec(2) DoubleVector tan_double2(@Vec(2) DoubleVector a) { return a.lanewise(VectorOperators.TAN); }
	public static @Vec(2) DoubleVector asin_double2(@Vec(2) DoubleVector a) { return a.lanewise(VectorOperators.ASIN); }
	public static @Vec(2) DoubleVector acos_double2(@Vec(2) DoubleVector a) { return a.lanewise(VectorOperators.ACOS); }
	public static @Vec(2) DoubleVector atan_double2(@Vec(2) DoubleVector a) { return a.lanewise(VectorOperators.ATAN); }
	public static @Vec(2) DoubleVector sinh_double2(@Vec(2) DoubleVector a) { return a.lanewise(VectorOperators.SINH); }
	public static @Vec(2) DoubleVector cosh_double2(@Vec(2) DoubleVector a) { return a.lanewise(VectorOperators.COSH); }
	public static @Vec(2) DoubleVector tanh_double2(@Vec(2) DoubleVector a) { return a.lanewise(VectorOperators.TANH); }
	public static @Vec(2) DoubleVector sqrt_double2(@Vec(2) DoubleVector a) { return a.lanewise(VectorOperators.SQRT); }
	public static @Vec(2) DoubleVector cbrt_double2(@Vec(2) DoubleVector a) { return a.lanewise(VectorOperators.CBRT); }
	public static @Vec(2) DoubleVector exp_double2(@Vec(2) DoubleVector a) { return a.lanewise(VectorOperators.EXP); }
	public static @Vec(2) DoubleVector log_double2(@Vec(2) DoubleVector a) { return a.lanewise(VectorOperators.LOG); }

	public static @Vec(2) DoubleVector add_double2_double(@Vec(2) DoubleVector a, double b) { return a.lanewise(VectorOperators.ADD, b); }
	public static @Vec(2) DoubleVector sub_double2_double(@Vec(2) DoubleVector a, double b) { return a.lanewise(VectorOperators.SUB, b); }
	public static @Vec(2) DoubleVector mul_double2_double(@Vec(2) DoubleVector a, double b) { return a.lanewise(VectorOperators.MUL, b); }
	public static @Vec(2) DoubleVector div_double2_double(@Vec(2) DoubleVector a, double b) { return a.lanewise(VectorOperators.DIV, b); }
	public static @Vec(2) DoubleVector pow_double2_double(@Vec(2) DoubleVector a, double b) { return a.lanewise(VectorOperators.POW, b); }
	public static @Vec(2) DoubleVector atan2_double2_double(@Vec(2) DoubleVector a, double b) { return a.lanewise(VectorOperators.ATAN2, b); }
	public static @Vec(2) DoubleVector min_double2_double(@Vec(2) DoubleVector a, double b) { return a.lanewise(VectorOperators.MIN, b); }
	public static @Vec(2) DoubleVector max_double2_double(@Vec(2) DoubleVector a, double b) { return a.lanewise(VectorOperators.MAX, b); }
	public static @Vec(2) DoubleVector add_double2_double2(@Vec(2) DoubleVector a, @Vec(2) DoubleVector b) { return a.lanewise(VectorOperators.ADD, b); }
	public static @Vec(2) DoubleVector sub_double2_double2(@Vec(2) DoubleVector a, @Vec(2) DoubleVector b) { return a.lanewise(VectorOperators.SUB, b); }
	public static @Vec(2) DoubleVector mul_double2_double2(@Vec(2) DoubleVector a, @Vec(2) DoubleVector b) { return a.lanewise(VectorOperators.MUL, b); }
	public static @Vec(2) DoubleVector div_double2_double2(@Vec(2) DoubleVector a, @Vec(2) DoubleVector b) { return a.lanewise(VectorOperators.DIV, b); }
	public static @Vec(2) DoubleVector pow_double2_double2(@Vec(2) DoubleVector a, @Vec(2) DoubleVector b) { return a.lanewise(VectorOperators.POW, b); }
	public static @Vec(2) DoubleVector atan2_double2_double2(@Vec(2) DoubleVector a, @Vec(2) DoubleVector b) { return a.lanewise(VectorOperators.ATAN2, b); }
	public static @Vec(2) DoubleVector min_double2_double2(@Vec(2) DoubleVector a, @Vec(2) DoubleVector b) { return a.lanewise(VectorOperators.MIN, b); }
	public static @Vec(2) DoubleVector max_double2_double2(@Vec(2) DoubleVector a, @Vec(2) DoubleVector b) { return a.lanewise(VectorOperators.MAX, b); }

	public static double dot_double2_double2(@Vec(2) DoubleVector a, @Vec(2) DoubleVector b) { return a.mul(b).reduceLanes(VectorOperators.ADD); }
	public static double lengthSquared_double2(@Vec(2) DoubleVector a) { return dot_double2_double2(a, a); }
	public static double length_double2(@Vec(2) DoubleVector a) { return Math.sqrt(dot_double2_double2(a, a)); }
	public static @Vec(2) DoubleVector normalize_double2(@Vec(2) DoubleVector a) { return a.div(length_double2(a)); }
	public static @Vec(2) DoubleVector mix_double2_double2_double2(@Vec(2) DoubleVector a, @Vec(2) DoubleVector b, @Vec(2) DoubleVector f) { return b.sub(a).mul(f).add(a); }
	public static @Vec(2) DoubleVector mix_double2_double2_double(@Vec(2) DoubleVector a, @Vec(2) DoubleVector b, double f) { return b.sub(a).mul(f).add(a); }

	public static @Vec(3) DoubleVector double3_from_int3(@Vec(3) IntVector a) { return (DoubleVector)a.convertShape(VectorOperators.I2D, DoubleVector.SPECIES_256, 0); }
	public static @Vec(3) DoubleVector double3_from_long3(@Vec(3) LongVector a) { return (DoubleVector)a.convert(VectorOperators.L2D, 0); }
	public static @Vec(3) DoubleVector double3_from_float3(@Vec(3) FloatVector a) { return (DoubleVector)a.convertShape(VectorOperators.F2D, DoubleVector.SPECIES_256, 0); }
	public static @Vec(3) DoubleVector double3_from_double3(@Vec(3) DoubleVector a) { return a; }
	public static @Vec(3) DoubleVector double3_from_double(double a) { return DoubleVector.broadcast(DoubleVector.SPECIES_256, a); }
	public static @Vec(3) DoubleVector double3_from_double_double_double(double a, double b, double c) { return DoubleVector.fromArray(DoubleVector.SPECIES_256, new double[] { a, b, c, 0 }, 0); }

	public static @Vec(3) DoubleVector neg_double3(@Vec(3) DoubleVector a) { return a.lanewise(VectorOperators.NEG); }
	public static @Vec(3) DoubleVector abs_double3(@Vec(3) DoubleVector a) { return a.lanewise(VectorOperators.ABS); }
	public static @Vec(3) DoubleVector sin_double3(@Vec(3) DoubleVector a) { return a.lanewise(VectorOperators.SIN); }
	public static @Vec(3) DoubleVector cos_double3(@Vec(3) DoubleVector a) { return a.lanewise(VectorOperators.COS); }
	public static @Vec(3) DoubleVector tan_double3(@Vec(3) DoubleVector a) { return a.lanewise(VectorOperators.TAN); }
	public static @Vec(3) DoubleVector asin_double3(@Vec(3) DoubleVector a) { return a.lanewise(VectorOperators.ASIN); }
	public static @Vec(3) DoubleVector acos_double3(@Vec(3) DoubleVector a) { return a.lanewise(VectorOperators.ACOS); }
	public static @Vec(3) DoubleVector atan_double3(@Vec(3) DoubleVector a) { return a.lanewise(VectorOperators.ATAN); }
	public static @Vec(3) DoubleVector sinh_double3(@Vec(3) DoubleVector a) { return a.lanewise(VectorOperators.SINH); }
	public static @Vec(3) DoubleVector cosh_double3(@Vec(3) DoubleVector a) { return a.lanewise(VectorOperators.COSH); }
	public static @Vec(3) DoubleVector tanh_double3(@Vec(3) DoubleVector a) { return a.lanewise(VectorOperators.TANH); }
	public static @Vec(3) DoubleVector sqrt_double3(@Vec(3) DoubleVector a) { return a.lanewise(VectorOperators.SQRT); }
	public static @Vec(3) DoubleVector cbrt_double3(@Vec(3) DoubleVector a) { return a.lanewise(VectorOperators.CBRT); }
	public static @Vec(3) DoubleVector exp_double3(@Vec(3) DoubleVector a) { return a.lanewise(VectorOperators.EXP); }
	public static @Vec(3) DoubleVector log_double3(@Vec(3) DoubleVector a) { return a.lanewise(VectorOperators.LOG); }

	public static @Vec(3) DoubleVector add_double3_double(@Vec(3) DoubleVector a, double b) { return a.lanewise(VectorOperators.ADD, b); }
	public static @Vec(3) DoubleVector sub_double3_double(@Vec(3) DoubleVector a, double b) { return a.lanewise(VectorOperators.SUB, b); }
	public static @Vec(3) DoubleVector mul_double3_double(@Vec(3) DoubleVector a, double b) { return a.lanewise(VectorOperators.MUL, b); }
	public static @Vec(3) DoubleVector div_double3_double(@Vec(3) DoubleVector a, double b) { return a.lanewise(VectorOperators.DIV, b); }
	public static @Vec(3) DoubleVector pow_double3_double(@Vec(3) DoubleVector a, double b) { return a.lanewise(VectorOperators.POW, b); }
	public static @Vec(3) DoubleVector atan2_double3_double(@Vec(3) DoubleVector a, double b) { return a.lanewise(VectorOperators.ATAN2, b); }
	public static @Vec(3) DoubleVector min_double3_double(@Vec(3) DoubleVector a, double b) { return a.lanewise(VectorOperators.MIN, b); }
	public static @Vec(3) DoubleVector max_double3_double(@Vec(3) DoubleVector a, double b) { return a.lanewise(VectorOperators.MAX, b); }
	public static @Vec(3) DoubleVector add_double3_double3(@Vec(3) DoubleVector a, @Vec(3) DoubleVector b) { return a.lanewise(VectorOperators.ADD, b); }
	public static @Vec(3) DoubleVector sub_double3_double3(@Vec(3) DoubleVector a, @Vec(3) DoubleVector b) { return a.lanewise(VectorOperators.SUB, b); }
	public static @Vec(3) DoubleVector mul_double3_double3(@Vec(3) DoubleVector a, @Vec(3) DoubleVector b) { return a.lanewise(VectorOperators.MUL, b); }
	public static @Vec(3) DoubleVector div_double3_double3(@Vec(3) DoubleVector a, @Vec(3) DoubleVector b) { return a.lanewise(VectorOperators.DIV, b); }
	public static @Vec(3) DoubleVector pow_double3_double3(@Vec(3) DoubleVector a, @Vec(3) DoubleVector b) { return a.lanewise(VectorOperators.POW, b); }
	public static @Vec(3) DoubleVector atan2_double3_double3(@Vec(3) DoubleVector a, @Vec(3) DoubleVector b) { return a.lanewise(VectorOperators.ATAN2, b); }
	public static @Vec(3) DoubleVector min_double3_double3(@Vec(3) DoubleVector a, @Vec(3) DoubleVector b) { return a.lanewise(VectorOperators.MIN, b); }
	public static @Vec(3) DoubleVector max_double3_double3(@Vec(3) DoubleVector a, @Vec(3) DoubleVector b) { return a.lanewise(VectorOperators.MAX, b); }

	public static double dot_double3_double3(@Vec(3) DoubleVector a, @Vec(3) DoubleVector b) { return a.mul(b).reduceLanes(VectorOperators.ADD); }
	public static double lengthSquared_double3(@Vec(3) DoubleVector a) { return dot_double3_double3(a, a); }
	public static double length_double3(@Vec(3) DoubleVector a) { return Math.sqrt(dot_double3_double3(a, a)); }
	public static @Vec(3) DoubleVector normalize_double3(@Vec(3) DoubleVector a) { return a.div(length_double3(a)); }
	public static @Vec(3) DoubleVector mix_double3_double3_double3(@Vec(3) DoubleVector a, @Vec(3) DoubleVector b, @Vec(3) DoubleVector f) { return b.sub(a).mul(f).add(a); }
	public static @Vec(3) DoubleVector mix_double3_double3_double(@Vec(3) DoubleVector a, @Vec(3) DoubleVector b, double f) { return b.sub(a).mul(f).add(a); }

	public static @Vec(4) DoubleVector double4_from_int4(@Vec(4) IntVector a) { return (DoubleVector)a.convertShape(VectorOperators.I2D, DoubleVector.SPECIES_256, 0); }
	public static @Vec(4) DoubleVector double4_from_long4(@Vec(4) LongVector a) { return (DoubleVector)a.convert(VectorOperators.L2D, 0); }
	public static @Vec(4) DoubleVector double4_from_float4(@Vec(4) FloatVector a) { return (DoubleVector)a.convertShape(VectorOperators.F2D, DoubleVector.SPECIES_256, 0); }
	public static @Vec(4) DoubleVector double4_from_double4(@Vec(4) DoubleVector a) { return a; }
	public static @Vec(4) DoubleVector double4_from_double(double a) { return DoubleVector.broadcast(DoubleVector.SPECIES_256, a); }
	public static @Vec(4) DoubleVector double4_from_double_double_double_double(double a, double b, double c, double d) { return DoubleVector.fromArray(DoubleVector.SPECIES_256, new double[] { a, b, c, d }, 0); }

	public static @Vec(4) DoubleVector neg_double4(@Vec(4) DoubleVector a) { return a.lanewise(VectorOperators.NEG); }
	public static @Vec(4) DoubleVector abs_double4(@Vec(4) DoubleVector a) { return a.lanewise(VectorOperators.ABS); }
	public static @Vec(4) DoubleVector sin_double4(@Vec(4) DoubleVector a) { return a.lanewise(VectorOperators.SIN); }
	public static @Vec(4) DoubleVector cos_double4(@Vec(4) DoubleVector a) { return a.lanewise(VectorOperators.COS); }
	public static @Vec(4) DoubleVector tan_double4(@Vec(4) DoubleVector a) { return a.lanewise(VectorOperators.TAN); }
	public static @Vec(4) DoubleVector asin_double4(@Vec(4) DoubleVector a) { return a.lanewise(VectorOperators.ASIN); }
	public static @Vec(4) DoubleVector acos_double4(@Vec(4) DoubleVector a) { return a.lanewise(VectorOperators.ACOS); }
	public static @Vec(4) DoubleVector atan_double4(@Vec(4) DoubleVector a) { return a.lanewise(VectorOperators.ATAN); }
	public static @Vec(4) DoubleVector sinh_double4(@Vec(4) DoubleVector a) { return a.lanewise(VectorOperators.SINH); }
	public static @Vec(4) DoubleVector cosh_double4(@Vec(4) DoubleVector a) { return a.lanewise(VectorOperators.COSH); }
	public static @Vec(4) DoubleVector tanh_double4(@Vec(4) DoubleVector a) { return a.lanewise(VectorOperators.TANH); }
	public static @Vec(4) DoubleVector sqrt_double4(@Vec(4) DoubleVector a) { return a.lanewise(VectorOperators.SQRT); }
	public static @Vec(4) DoubleVector cbrt_double4(@Vec(4) DoubleVector a) { return a.lanewise(VectorOperators.CBRT); }
	public static @Vec(4) DoubleVector exp_double4(@Vec(4) DoubleVector a) { return a.lanewise(VectorOperators.EXP); }
	public static @Vec(4) DoubleVector log_double4(@Vec(4) DoubleVector a) { return a.lanewise(VectorOperators.LOG); }

	public static @Vec(4) DoubleVector add_double4_double(@Vec(4) DoubleVector a, double b) { return a.lanewise(VectorOperators.ADD, b); }
	public static @Vec(4) DoubleVector sub_double4_double(@Vec(4) DoubleVector a, double b) { return a.lanewise(VectorOperators.SUB, b); }
	public static @Vec(4) DoubleVector mul_double4_double(@Vec(4) DoubleVector a, double b) { return a.lanewise(VectorOperators.MUL, b); }
	public static @Vec(4) DoubleVector div_double4_double(@Vec(4) DoubleVector a, double b) { return a.lanewise(VectorOperators.DIV, b); }
	public static @Vec(4) DoubleVector pow_double4_double(@Vec(4) DoubleVector a, double b) { return a.lanewise(VectorOperators.POW, b); }
	public static @Vec(4) DoubleVector atan2_double4_double(@Vec(4) DoubleVector a, double b) { return a.lanewise(VectorOperators.ATAN2, b); }
	public static @Vec(4) DoubleVector min_double4_double(@Vec(4) DoubleVector a, double b) { return a.lanewise(VectorOperators.MIN, b); }
	public static @Vec(4) DoubleVector max_double4_double(@Vec(4) DoubleVector a, double b) { return a.lanewise(VectorOperators.MAX, b); }
	public static @Vec(4) DoubleVector add_double4_double4(@Vec(4) DoubleVector a, @Vec(4) DoubleVector b) { return a.lanewise(VectorOperators.ADD, b); }
	public static @Vec(4) DoubleVector sub_double4_double4(@Vec(4) DoubleVector a, @Vec(4) DoubleVector b) { return a.lanewise(VectorOperators.SUB, b); }
	public static @Vec(4) DoubleVector mul_double4_double4(@Vec(4) DoubleVector a, @Vec(4) DoubleVector b) { return a.lanewise(VectorOperators.MUL, b); }
	public static @Vec(4) DoubleVector div_double4_double4(@Vec(4) DoubleVector a, @Vec(4) DoubleVector b) { return a.lanewise(VectorOperators.DIV, b); }
	public static @Vec(4) DoubleVector pow_double4_double4(@Vec(4) DoubleVector a, @Vec(4) DoubleVector b) { return a.lanewise(VectorOperators.POW, b); }
	public static @Vec(4) DoubleVector atan2_double4_double4(@Vec(4) DoubleVector a, @Vec(4) DoubleVector b) { return a.lanewise(VectorOperators.ATAN2, b); }
	public static @Vec(4) DoubleVector min_double4_double4(@Vec(4) DoubleVector a, @Vec(4) DoubleVector b) { return a.lanewise(VectorOperators.MIN, b); }
	public static @Vec(4) DoubleVector max_double4_double4(@Vec(4) DoubleVector a, @Vec(4) DoubleVector b) { return a.lanewise(VectorOperators.MAX, b); }

	public static double dot_double4_double4(@Vec(4) DoubleVector a, @Vec(4) DoubleVector b) { return a.mul(b).reduceLanes(VectorOperators.ADD); }
	public static double lengthSquared_double4(@Vec(4) DoubleVector a) { return dot_double4_double4(a, a); }
	public static double length_double4(@Vec(4) DoubleVector a) { return Math.sqrt(dot_double4_double4(a, a)); }
	public static @Vec(4) DoubleVector normalize_double4(@Vec(4) DoubleVector a) { return a.div(length_double4(a)); }
	public static @Vec(4) DoubleVector mix_double4_double4_double4(@Vec(4) DoubleVector a, @Vec(4) DoubleVector b, @Vec(4) DoubleVector f) { return b.sub(a).mul(f).add(a); }
	public static @Vec(4) DoubleVector mix_double4_double4_double(@Vec(4) DoubleVector a, @Vec(4) DoubleVector b, double f) { return b.sub(a).mul(f).add(a); }

	public static BigInteger neg_bigint(BigInteger a) { return a.negate(); }
	public static BigInteger not_bigint(BigInteger a) { return a.not(); }
	public static BigInteger abs_bigint(BigInteger a) { return a.abs(); }

	public static BigInteger add_bigint_bigint(BigInteger a, BigInteger b) { return a.add(b); }
	public static BigInteger sub_bigint_bigint(BigInteger a, BigInteger b) { return a.subtract(b); }
	public static BigInteger mul_bigint_bigint(BigInteger a, BigInteger b) { return a.multiply(b); }
	public static BigInteger div_bigint_bigint(BigInteger a, BigInteger b) { return a.divide(b); }
	public static BigInteger pow_bigint_bigint(BigInteger a, BigInteger b) { return a.pow(b.intValueExact()); }
	public static BigInteger and_bigint_bigint(BigInteger a, BigInteger b) { return a.and(b); }
	public static BigInteger or_bigint_bigint(BigInteger a, BigInteger b) { return a.or(b); }
	public static BigInteger xor_bigint_bigint(BigInteger a, BigInteger b) { return a.xor(b); }
	public static BigInteger lshl_bigint_bigint(BigInteger a, BigInteger b) { return a.shiftLeft(b.intValueExact()); }
	public static BigInteger ashr_bigint_bigint(BigInteger a, BigInteger b) { return a.shiftRight(b.intValueExact()); }
	public static BigInteger min_bigint_bigint(BigInteger a, BigInteger b) { return a.min(b); }
	public static BigInteger max_bigint_bigint(BigInteger a, BigInteger b) { return a.max(b); }

	public static BigDecimal neg_bigdec(BigDecimal a) { return a.negate(); }
	public static BigDecimal abs_bigdec(BigDecimal a) { return a.abs(); }
	public static BigDecimal sin_bigdec(BigDecimal a) { return new BigDecimal(Math.sin(a.doubleValue())); }
	public static BigDecimal cos_bigdec(BigDecimal a) { return new BigDecimal(Math.cos(a.doubleValue())); }
	public static BigDecimal tan_bigdec(BigDecimal a) { return new BigDecimal(Math.tan(a.doubleValue())); }
	public static BigDecimal asin_bigdec(BigDecimal a) { return new BigDecimal(Math.asin(a.doubleValue())); }
	public static BigDecimal acos_bigdec(BigDecimal a) { return new BigDecimal(Math.acos(a.doubleValue())); }
	public static BigDecimal atan_bigdec(BigDecimal a) { return new BigDecimal(Math.atan(a.doubleValue())); }
	public static BigDecimal sinh_bigdec(BigDecimal a) { return new BigDecimal(Math.sinh(a.doubleValue())); }
	public static BigDecimal cosh_bigdec(BigDecimal a) { return new BigDecimal(Math.cosh(a.doubleValue())); }
	public static BigDecimal tanh_bigdec(BigDecimal a) { return new BigDecimal(Math.tanh(a.doubleValue())); }
	public static BigDecimal sqrt_bigdec(BigDecimal a) { return a.sqrt(MathContext.DECIMAL128); }
	public static BigDecimal cbrt_bigdec(BigDecimal a) { return new BigDecimal(Math.cbrt(a.doubleValue())); }
	public static BigDecimal exp_bigdec(BigDecimal a) { return new BigDecimal(Math.exp(a.doubleValue())); }
	public static BigDecimal log_bigdec(BigDecimal a) { return new BigDecimal(Math.log(a.doubleValue())); }

	public static BigDecimal add_bigdec_bigdec(BigDecimal a, BigDecimal b) { return a.add(b); }
	public static BigDecimal sub_bigdec_bigdec(BigDecimal a, BigDecimal b) { return a.subtract(b); }
	public static BigDecimal mul_bigdec_bigdec(BigDecimal a, BigDecimal b) { return a.multiply(b, MathContext.DECIMAL128); }
	public static BigDecimal div_bigdec_bigdec(BigDecimal a, BigDecimal b) { return a.divide(b, MathContext.DECIMAL128); }
	public static BigDecimal pow_bigdec_bigdec(BigDecimal a, BigDecimal b) { return new BigDecimal(Math.pow(a.doubleValue(), b.doubleValue())); }
	public static BigDecimal atan2_bigdec_bigdec(BigDecimal a, BigDecimal b) { return new BigDecimal(Math.atan2(a.doubleValue(), b.doubleValue())); }
	public static BigDecimal min_bigdec_bigdec(BigDecimal a, BigDecimal b) { return a.min(b); }
	public static BigDecimal max_bigdec_bigdec(BigDecimal a, BigDecimal b) { return a.max(b); }

	public static BigDecimal mix_bigdec_bigdec_bigdec(BigDecimal a, BigDecimal b, BigDecimal f) { return b.subtract(a).multiply(f, MathContext.DECIMAL128).add(a); }
}